### ISSUE TITLE
Should --recurse-subgroups process projects?

### ISSUE THREAD

**Issue by rrotaru** [gitlabform/gitlabform#1001]
I was reading through #613 and #828 where it sounded like the `--recurse-subgroups` feature was added as a way to process everything under a target path (e.g. `group/subgroup/**`).

However, in my testing, it looks like _not_ including `--recurse-subgroups` includes all child projects, and including `--recurse-subgroups` _omits_ all child projects but then includes all child groups.

Example config:
```yml
config_version: 3

gitlab:
  url: https://gitlab.com/

projects_and_groups:
  "my-company/main-org/sub-org/scratch/*":
    group_settings:
      share_with_group_lock: false
    project_settings:
      allow_merge_on_skipped_pipeline: false
  "my-company/main-org/sub-org/scratch/test-subgroup-1/*":
    group_settings:
      share_with_group_lock: true
    project_settings:
      allow_merge_on_skipped_pipeline: true
```

Output:
```
### This processes 1 group and 5 projects
❯ pipx run gitlabform my-company/main-org/sub-org/scratch --diff-only-changed --config scratch-config.yml --noop
🏗 GitLabForm version: 4.2.0 = the latest stable 😊
Warning: Connected as non-admin. You may encounter permission issues.
Running in dry-run mode...
>>> Getting requested groups or projects...
:: # of groups to process: 1
:: # of projects to process: 5
@ (1/1) Processing group: my-company/main-org/sub-org/scratch
* (1/5) Processing project: my-company/main-org/sub-org/scratch/my-awesome-group/my-awesome-project
* (2/5) Processing project: my-company/main-org/sub-org/scratch/my-awesome-group/my-not-so-awesome-project
* (3/5) Processing project: my-company/main-org/sub-org/scratch/test-project-1
* (4/5) Processing project: my-company/main-org/sub-org/scratch/test-subgroup-1/test-sub-subgroup-2/test-sub-sub-project-1
* (5/5) Processing project: my-company/main-org/sub-org/scratch/test-subgroup-1/test-subproject-1
:: # of groups processed successfully: 1
:: # of projects processed successfully: 5
:: All requested groups/projects processed successfully! ✨

### This processes 6 groups and 0 projects
❯ pipx run gitlabform my-company/main-org/sub-org/scratch --diff-only-changed --config scratch-config.yml --noop --recurse-subgroups
🏗 GitLabForm version: 4.2.0 = the latest stable 😊
Warning: Connected as non-admin. You may encounter permission issues.
Running in dry-run mode...
>>> Getting requested groups or projects...
:: # of groups to process: 6
:: # of projects to process: 0
@ (1/6) Processing group: my-company/main-org/sub-org/scratch
@ (2/6) Processing group: my-company/main-org/sub-org/scratch/my-awesome-group
@ (3/6) Processing group: my-company/main-org/sub-org/scratch/my-awesome-group/not-so-awesome-subgroup
@ (4/6) Processing group: my-company/main-org/sub-org/scratch/test-subgroup-1
@ (5/6) Processing group: my-company/main-org/sub-org/scratch/test-subgroup-1/test-sub-subgroup-2
@ (6/6) Processing group: my-company/main-org/sub-org/scratch/testing-saml-membership
:: # of groups processed successfully: 6
:: # of projects processed successfully: 0
:: All requested groups/projects processed successfully! ✨
```

I'm looking to see how I can run against all subprojects _and_ subgroups when not using `ALL` or `ALL_DEFINED`, since those are very slow performance-wise when running against a large org (the "getting all projects I can modify" step can take >10 minutes).

I'd like to understand why `recurse_subgroups=False` recurses just subprojects, and `recurse_subgroups=True` recurses just subgroups.
