### ISSUE TITLE
Unable deactivate service: jira

### ISSUE THREAD

**Issue by glensc** [gitlabform/gitlabform#102]
I'd like to deactivate a service (not delete):

```yaml
project_settings:
  "glen/playground":
    services:
      jira:
        active: false
```

but this gives api error:

```
gitlabform.gitlab.core.UnexpectedResponseException: Request url='https://gitlab.example.net/api/v4/projects/glen%2Fplayground/services/jira', method=PUT, data='None' failed - expected code(s) [200, 201], got code 400 & body: 'b'{"error":"url is missing, username is missing, password is missing"}''
```

however, it's perfectly possible to do that from gitlab own UI. just click on the active checkbox and save.
