### ISSUE TITLE
Using the premium only branch protection rules causes unnecessary updating

### ISSUE THREAD

**Issue by andrewjw** [gitlabform/gitlabform#1034]
If you use the premium only branch protection rules (allowed_to_push, allowed_to_merge) then the diffing doesn't work and it unprotects and then reprotects the branches every run. This causes extra api load, and spams the project's audit logs.

Example config
```
    main:
      protected: true
      allowed_to_push:
        - user: username
      allowed_to_merge:
        - access_level: developer
      code_owner_approval_required: true
```

This gets turned into the following Python object...

```
{'protected': True, 'allowed_to_push': [{'user_id': 1767}], 'allowed_to_merge': [{'access_level': 30}], 'code_owner_approval_required': True}
```

The data returned from the GitLab API is:

```
{'project_id': '20306', 'id': 28843761, 'name': 'master', 'push_access_levels': [{'id': 28960972, 'access_level': 40, 'access_level_description': 'username', 'deploy_key_id': None, 'user_id': 1767, 'group_id': None}], 'merge_access_levels': [{'id': 28981208, 'access_level': 30, 'access_level_description': 'Developers + Maintainers', 'user_id': None, 'group_id': None}], 'allow_force_push': False, 'unprotect_access_levels': [{'id': 26711591, 'access_level': 40, 'access_level_description': 'Maintainers', 'user_id': None, 'group_id': None}], 'code_owner_approval_required': True, 'inherited': False}
```

and since they don't match, the branch is unprotected and reprotected.

**GitLabForm version**

`GitLabForm version: 4.2.5`

**GitLab version**

`17.11.2` (self managed, premium tier)
