### ISSUE TITLE
Further enhancements to config syntax/structure

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#222]
I'm really happy to see that V2 has been released. Just reading the configuration example so that I can start using it. I'm still finding some areas where the config structure is a bit ambiguous, misleading, or not intuitive. Or, maybe I'm just interpreting it incorrectly.

<details>
  <summary>Here is a truncated version of the example config from this repo.</summary>

```yml
#
# You can define settings on 3 levels here:
# * common - for ALL projects in ALL groups - under "*" key
# * group/subgroup - for ALL projects in selected group/subgroup (recursively) - under keys ending with "/*"
# * project - for single projects
#
# Each level is optional.
#
# To generate effective settings to apply for a given project, if it is configured on more than one level
# (for example you run it for "my-group/my-project" with the example configuration below, where this project will
# take configuration from all 3 levels), GitLabForm will merge those configurations.
#
# Merging is additive, so for sections like `deploy_keys`, `secret_variables`, `hooks' on each lower level
# the effective configuration will contain elements from higher levels plus elements from lower levels.
#
# Exception: when `skip: true` is set on a more specific level, given config section is not set AT ALL for given project.
#

projects_and_groups:
  "*":
    # common settings for ALL projects in ALL groups

    # keys and values here are as described at https://docs.gitlab.com/ee/api/project_level_variables.html#create-variable
    secret_variables:
      ...

    # keys and values here are as described at https://docs.gitlab.com/ee/api/group_level_variables.html#create-variable
    group_secret_variables:
      ...

  # settings for ALL projects in 'my-group' group
  "my-group/*":
    ...

    # keys and values here are as described at https://docs.gitlab.com/ee/api/project_level_variables.html#create-variable
    secret_variables:
      ...

    # keys and values here are as described at https://docs.gitlab.com/ee/api/group_level_variables.html#create-variable
    group_secret_variables:
      ...

    # keys and values here are as described at https://docs.gitlab.com/ce/api/projects.html#edit-project
    project_settings:
      ...

    # this is for adding/changing the access level of group members - only users can be them
    # for removing users please see the flag below.
    #
    # keys names are user names and values are as parameters described at
    # https://docs.gitlab.com/ee/api/members.html#add-a-member-to-a-group-or-project
    group_members:
      my-user:
        access_level: 50 # = Owner, see "valid access levels" at https://docs.gitlab.com/ee/api/members.html

    # if this flag is set to 'true', then removing a user the above config will remove the user from the group
    # note: you have to keep at least 1 user with Owner level (50) - it's required by GitLab
    enforce_group_members: true  # default: false

    # keys names are tags names and values are as parameters described at
    # https://docs.gitlab.com/ee/api/protected_tags.html
    tags:
      "v*":
        protected: true
        create_access_level: 40 # = Maintainer, see "valid access levels" at https://docs.gitlab.com/ee/api/members.html

    # service names are as in the endpoints described at https://docs.gitlab.com/ce/api/services.html
    # hashes under those name correspond to the parameters described for given service there
    # except where services are deleted with `delete: true`
    services:
      slack:
        delete: true
      drone-ci:
        delete: true
      jira:
        active: true
        url: https://jira.yourcompany.com
        username: foo
        password: bar

    # key names here are hook URLs and values are as parameters described at
    # https://docs.gitlab.com/ee/api/projects.html#edit-project-hook
    # except where hooks are deleted with `delete: true`
    hooks:
      "http://host.domain.com/some-old-hook-you-want-to-remove-from-config":
        delete: true
      "http://127.0.0.1:5000/hooks/merge-request":
        push_events: false # this is set to true by GitLab API by default
        merge_requests_events: true
        token: some_secret_auth_token

  # settings for ALL projects in 'old-projects-group' group
  old-projects-group/*:
    # this will archive all the projects in the 'old-projects-group' group
    project:
      # note: you can lso unarchive a project by setting this to 'true' but then you need to run
      # the app WITHOUT --skip-archived-projects flag
      archive: true

  group-with-spammy-projects/*:
    # configures settings for the 'group-with-spammy-projects' group
    group_settings:
      # keys and values here are as described at https://docs.gitlab.com/ee/api/groups.html#update-group
      emails_disabled: true

  # settings specific to 'my-group/my-project1' project
  "my-group/my-project1":
    project_settings:
      # this will make this project settings set to values defined on a group level, but with this single parameter
      # overriden
      visibility: private

    deploy_keys:
      # see comment above - this key will be ADDED to the keys configured on a group level
      one_more_deploy_key:
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDB2QKx6BPzL...
        title: ssh_key_name_that_is_shown_in_gitlab_3
        can_push: false

    secret_variables:
      # CI CD variable for this project. Variables can be scoped to an "environment".
      # Scoping to environment also allows using the same "key" name for multiple variables.
      # This can simplify CI Config file because the appropriate variable will be exposed
      # by GitLab to the job that is targetting a given environment. If the same "key" name
      # is used for different environments, you'll need to add filter[environment_scope] to
      # configuration as shown below.
      aws_access_key_id_for_deploying_in_production:
        key: APP_HOST_AWS_ACCESS_KEY_ID
        value: "prod-value-1234"
        protected: true
        masked: true
        environment_scope: production
        filter[environment_scope]: production
      aws_access_key_id_for_deploying_in_staging:
        key: APP_HOST_AWS_ACCESS_KEY_ID
        value: "staging-value-1234"
        protected: true
        masked: true
        environment_scope: staging
        filter[environment_scope]: staging

    # this is for adding/changing the access level of project members - groups or users
    # note: removing members from the config DOES NOT remove their access!
    #
    # keys names are members/groups names and values are as parameters described at
    # https://docs.gitlab.com/ee/api/projects.html#share-project-with-group
    # https://docs.gitlab.com/ee/api/members.html#add-a-member-to-a-group-or-project
    members:
      groups:
        my-group:
          group_access: 40 # = Maintainer, see "valid access levels" at https://docs.gitlab.com/ee/api/members.html
        my-other-group/subgroup:
          group_access: 40 # Maintainer
      users:
        my-user:
          access_level: 40 # Maintainer
          expires_at: 2019-09-26

# this will skip these projects from being processed
skip_projects:
  - my-group/this-project-will-not-be-processed-with-gitlabform-when-running-for-my-group
  - my-group/and-this-too

# this will skip these groups from being processed
skip_groups:
  - my-other-group

```
</details>

Majority of the configs are about "project" settings. There are some configs for the "group" itself, but they are somewhat unnatural to follow, I think.

We have `secret_variables` for project level variables and `group_secret_variables` for group level variables. We have `project_settings` and `group_settings`. We have `group_members` but don't have `project_members`; it's just `members`. Similarly,  we only have `deploy_keys` and in the following example, it's not intuitive to follow. Here the deploy key is being added at the group level instead of project level even though the config is nested under a project config (i.e. `my-group/my-project1`).

```yml
  # settings specific to 'my-group/my-project1' project
  "my-group/my-project1":
    project_settings:
      # this will make this project settings set to values defined on a group level, but with this single parameter
      # overriden
      visibility: private

    deploy_keys:
      # see comment above - this key will be ADDED to the keys configured on a group level
      one_more_deploy_key:
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDB2QKx6BPzL...
        title: ssh_key_name_that_is_shown_in_gitlab_3
        can_push: false
```

Now that we have pattern matching, maybe that can help making the config structure more intuitive. For example:

```yml
my-gitlab-config:
  ## Common settings for all groups and projects. These will be merged with lower level config and then executed
  "*":
    "secret_variables": ...
    "description": ...
    "members": ...

  "group_settings":
    ## Config for this group settings
    "deploy_keys": ...
    "secret-variables": ...
    "members": ...
    ## any other settings applicable to this group

  "project_settings":
    ## Config for this group settings
    "deploy_keys": ...
    "secret-variables": ...
    "members": ...
    "branches": ...
    ## any other settings applicable to this group

  ## End of common settings

  "product/*":
    ## Config for all projects under this group
    "project_settings":
      "deploy_keys": ...
      "secret_variables": ....
      "members": ...
      ## any other project level settings goes here

  "product/special-project":
    ## Config for this project only
    "project_settings":
      "deploy_keys": ...
      "secret_variables": ....
      "members": ...
      ## any other project level settings goes here

  "product/special-group":
    ## Config for this sub-group only
    "group_settings":
      "deploy_keys": ...
      "secret_variables": ....
      "members": ...
      ## any other group level settings goes here
```

I may have missed a few key points but just wanted to jot down my thought on the new config syntax as I'm getting ready to move to V2.

**Comment by amimas** [comment]
I just realized that there is some collision between terms with the suggestion I posted above. For example, `project_settings` config key is associated with only part of the settings because of how GitLab's API is organized. Other project level settings (i.e. merge reqeust, approvals, branches, variables, etc.) are not in `project_settings`.

Here's a revised version, if it makes sense at all 😄. Basically, I'm assigning `gf_` prefix to separate out that the containing configs are for gitlabform to process accordingly.


```yml
my-gitlab-config:
  ## Common settings for all groups and projects. These will be merged with lower level config and then executed
  "*":
    "secret_variables": ...
    "description": ...
    "members": ...
    "group_settings": ...
    "project_settings": ....

  "gf_group_settings":
    ## Config for this group settings
    "deploy_keys": ...
    "secret-variables": ...
    "members": ...
    "group_settings": ...
    ## any other settings applicable to this group

  "gf_project_settings":
    ## Config for this group settings
    "deploy_keys": ...
    "secret-variables": ...
    "members": ...
    "branches": ...
    "project_settings": ...
    "merge_requests": ...
    ## any other settings applicable to this group

  ## End of common settings

  "product/*":
    ## Config for all projects under this group
    "gf_project_settings":
      "deploy_keys": ...
      "secret_variables": ....
      "members": ...
      "project_settings": ...
      "merge_requests": ....
      ## any other project level settings goes here

  "product/special-project":
    ## Config for this project only
    "gf_project_settings":
      "deploy_keys": ...
      "secret_variables": ....
      "members": ...
      "project_settings": ....
      "merge_requests": ....
      ## any other project level settings goes here

  "product/special-group":
    ## Config for this sub-group only
    "gf_group_settings":
      "deploy_keys": ...
      "secret_variables": ....
      "members": ...
      "group_settings": ....
      ## any other group level settings goes here
```
