### ISSUE TITLE
skip_groups doesn't work for subgroup

### ISSUE THREAD

**Issue by aleung** [gitlabform/gitlabform#275]
**Describe the bug**

On our GitLab server, there is a top level group `ei` and several levels of subgroups under it.

My config file has subgroup name set into `skip_groups`:

```yml
projects_and_groups:
  "*":
    # configurations
skip_groups:
  - ei/demo
```

Run gitlabform on the group `ei`:
```
gitlabform ei
```

I expect the projects `ei/demo/*` are skipped, but all of them had be configured.

Read the source code, I saw that `_remove_skipped_groups` is called only when target is `ALL` or `ALL_DEFINED` and isn't applied if target is a group.

https://github.com/egnyte/gitlabform/blob/dbb53da60c5366295a4269fec2577b34be1a862f/gitlabform/input.py#L28

**GitLabForm version**

2.2.0
