### ISSUE TITLE
Inheritance break validation function is improperly invalidating

### ISSUE THREAD

**Issue by ep-linden** [gitlabform/gitlabform#373]
**Describe the bug**

Given a config such as this:

```
projects_and_groups:
  parent/*:
    group_settings:
      description: parent group settings
      project_creation_level: developer

    members:
      enforce: true
      groups:
        group1:
          group_access: developer
        group2:
          group_access: developer
        group3:
          group_access: developer

  commerce/playground/*:
    group_settings:
      description: ''
      project_creation_level: maintainer

    members:
      inherit: false
      enforce: true
      groups:
        group3:
          group_access: maintainer

```

Since a subgroup is considered both a group and a subgroup,  when `inherit: false` is set under members in the subgroup to break the inheritance from the parent group, the break-inheritance validation function throws an error.

**GitLabForm version**

🏗  GitLabForm version: 2.11.1 = the latest stable 😊

**GitLab version**

GitLab Enterprise Edition 14.10.2-ee
