### ISSUE TITLE
Group CI/CD Variables (group_secret_variables) not honoring protected and masked values

### ISSUE THREAD

**Issue by rossbeehler** [gitlabform/gitlabform#384]
**Describe the bug**

When adding a `group_secret_variable` like this:

``` yaml
    group_secret_variables:
      variable1:
        key: VARIABLE1
        value: VALUE1
        protected: false
        masked: false
```

The variable will be created with `protected` and `masked` as `true`.

Successive runs shows that the difference is understood:

```
Editing VARIABLE1 of group_secret_variables in group1
```

But it still doesn't update their values.

Only when you manually change the values to both `false` in the GitLab UI, will you get the following verbose output from gitlabform:

```
VARIABLE1 of group_secret_variables in group1 doesn't need an update.
```

**GitLabForm version**

GitLabForm version: 2.11.1.post3 = the latest stable

**GitLab version**

GitLab.com SaaS Premium Subscription on 15.1-pre
