### ISSUE TITLE
MR approvers not working in some cases

### ISSUE THREAD

**Issue by weakcamel** [gitlabform/gitlabform#388]
In several latest Gitlab releases, Gitlab doesn't support the "approvers" endpoint which gitlabform has historically been using to manage approvers... and then also approver rule (a single one).

That endpoint is no longer available on Gitlab 13, 14, 15 and I'm aware that https://github.com/gitlabform/gitlabform/pull/176 is unlikely to be merged in. It's unfortunate yet completely understandable  - if this functionality isn't essential for the author and community hasn't managed to provide a fix (well, myself included), it's only fair.

I wonder though, could it be useful perhaps to remove managing approvers from the feature list and mark using `approvers` + `approver_group` keys as obsolete? As it is, running Gitlabform accepts them but any configuration given has no effect.

**Comment by gdubicki** [comment]
Hi @weakcamel!

I am surprised that you write that it doesn’t work because we are using this at Egnyte with semi-latest GitLab and we do run the acceptance tests for it with the latest GitLab.

Perhaps the problem is that we use an old GitLab license for all of these purposes and it allows only a single approver rule?

We will upgrade to the Premium license in a month or two so then I can test and fix the bug.

If you or anyone wants to help make it happen faster then you either would have to share you license (it is allowed for dev purposes) securely with this project or just provide a PR with the fix.

Whatever we will do please know that this feature is NOT abandoned and will be working again. :)

**Comment by weakcamel** [comment]
Hello,

I've just checked again. Sorry for a false alert (again), it does seem to work if you use `remove_other_approval_rules` (although I was 99.99% sure I tested that with this flag as well - maybe just at the wrong level in Yaml tree?).

> Perhaps the problem is that we use an old GitLab license for all of these purposes and it allows only a single approver rule?

The `approvers` endpoint has been removed in 13.11 (https://gitlab.com/gitlab-org/gitlab/-/blob/master/CHANGELOG-EE.md#13110-2021-04-22) and I thought gitlabform was using that, but no longer - that was my wrong assumption.

I just ran gitlabform with `-d` against a project and fiddled with Gitlab's UI and I think I know a bit more about what's happening: if you remove all custom rules, there's still one applying to "Any eligible approver" which you can't remove from the UI, but can with REST API:

![Screenshot 2022-06-24 at 09 03 40](https://user-images.githubusercontent.com/2445059/175492536-4dc40dcd-595d-4d80-b134-b532a613518d.png)

After deleting the rule with REST, this UI element is still there, just showing `0`. After adding `remove_other_approval_rules: true` this works quice nicely now. I'm really confused what I was doing wrong before! 

I'm going to apply my changes to multiple projects now and verify. If there are any new findings, I'll post them here.

**Comment by weakcamel** [comment]
I know now what happened: what I was initially trying to achieve is reset the approvals to this single "Any eligible user" group

I tried that by providing:

```
  projects_and_groups:
  'mygroup/*':
    merge_requests:
      approvals:
        approvals_before_merge: 1
        reset_approvals_on_push: false
        merge_requests_author_approval: true
        disable_overriding_approvers_per_merge_request: true
      approver_groups: []
      remove_other_approval_rules: true
```

but that created me an empty approval rule:

![Screenshot 2022-06-24 at 09 52 40](https://user-images.githubusercontent.com/2445059/175500406-b9d4e31a-c96a-4dbb-867c-a62709de722e.png)

So I removed the `approver_groups` key entirely but then gitlabform simply doesn't process this at all, whether `remove_other_approval_rules` is `true` or `false`.

Is there perhaps some special syntax in which one can remove the custom rules entirely?

**Comment by gdubicki** [comment]
Do I get it right that you want to keep the default "Any eligible user" rule with "Approvals required" set to `approvals_before_merge` value and not add the `Approvers (configured using GitLabForm)` rule at all, @weakcamel?

**Comment by gdubicki** [comment]
I would have to check what are the options to restore the default „any eligible dev” approval rule with the API and we should come up with a proposal for config syntax that would result in it. Any suggestions about the latter, @weakcamel?

**Comment by weakcamel** [comment]
How I got to the desired state was to remove all custom rules set and then set 1 in the UI for the built-in.

The built-in rule is tricky; it doesn't show in the Gitlab's UI unless the value for number of approvers was changed from the default 0; this means gitlabform might need to just delete all rules entirely and create this one back.

I was able to put it back in with `python-gitlab`:

```
$ gitlab project-approval-rule create --project-id group/project --approvals-required 1 --name 'All Members'
id: 667
$ gitlab -o json project-approval-rule list --project-id group/project
[{"id": 667, "name": "All Members", "rule_type": "any_approver", "eligible_approvers": [], "approvals_required": 1, "users": [], "groups": [], "contains_hidden_groups": false, "protected_branches": []}]
```

In debug mode to show the REST API:

```
$ gitlab -d project-approval-rule create --project-id group/project --approvals-required 1 --name 'All Members'
send: b'POST /api/v4/projects/group%2Fproject/approval_rules HTTP/1.1\r\nHost: gitlab.example.com\r\nUser-Agent: python-gitlab/3.6.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nConnection: keep-alive\r\nPRIVATE-TOKEN: <REDACTED>\r\nContent-type: application/json\r\nContent-Length: 50\r\nAuthorization: Basic <REDACTED>\r\n\r\n'
send: b'{"name": "All Members", "approvals_required": "1"}'
reply: 'HTTP/1.1 201 Created\r\n'
header: Server: nginx
header: Date: Mon, 04 Jul 2022 09:05:54 GMT
header: Content-Type: application/json
header: Content-Length: 183
header: Connection: keep-alive
header: Cache-Control: max-age=0, private, must-revalidate
header: Etag: W/"10ed494086d120718faec281193eecfc"
header: Vary: Origin
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-Gitlab-Feature-Category: source_code_management
header: X-Request-Id: 01G747B1WVB3KVP78SW37SFKSB
header: X-Runtime: 0.087482
header: Strict-Transport-Security: max-age=31536000
header: Referrer-Policy: strict-origin-when-cross-origin
DEBUG:urllib3.connectionpool:https://gitlab.example.com:443 "POST /api/v4/projects/group%2Fproject/approval_rules HTTP/1.1" 201 183
id: 668
```

**Comment by gdubicki** [comment]
I am beginning working on this feature. For a start I would like to get feedback on a configuration syntax proposal.

The current syntax, f.e.:
```yaml
    merge_requests:
      approvals:
        approvals_before_merge: 2
        reset_approvals_on_push: false
        disable_overriding_approvers_per_merge_request: true
        merge_requests_author_approval: false
      approvers:
        - user1
        - user2
      approver_groups:
        - my-group
        - my-group1/subgroup
        - my-group2/subgroup/subsubgroup
      remove_other_approval_rules: false
```
...would remain working for users who don't need more than 1 approval rule and related syntax complexity. The single approval rule managed this way would keep its current name - "Approvers (configured using GitLabForm)".

But the `remove_other_approval_rules` key would be deprecated and a more standard `enforce: true` key would replace it.

So the new syntax would look like this:
```yaml
    merge_requests:
      approvals:
        # (no changes here)
        reset_approvals_on_push: false
        disable_overriding_approvers_per_merge_request: true
        merge_requests_author_approval: false
      approval_rules:
      	standard:
          approvals_required: 2
          name: "Regular approvers"
          groups:
            - developers
      	security:
          approvals_required: 2
          name: "Extra Security Team approval for selected branches"
          users:
            - secmember1
            - secmember2
          protected_branches:
            - sensitive-branch 
        enforce: true 
```
...where:
* "standard" and "security" are just labels,
* the values under these keys are like in https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule but:
  * instead of "group_ids" there would be "groups" (names)
  * instead of "protected_branch_ids" there would be "protected_branches" (names)
  * instead of "user_ids" there would be "users" (names)

So to achieve what you wanted, @weakcamel, we would need to use the following config syntax:
```yaml
    merge_requests:
      # (...)
      approval_rules:
      	default:
          approvals_required: 1
          name: "All Members"
          rule_type: any_approver
        enforce: true 
```

Opinions?

cc @jimisola @amimas

**Comment by amimas** [comment]
The proposal looks good to me @gdubicki .

For the new syntax of setting custom approval rules:

> the values under these keys are like in https://docs.gitlab.com/ee/api/merge_request_approvals.html#create-project-level-rule but:
>
>    instead of "group_ids" there would be "groups" (names)
>    instead of "protected_branch_ids" there would be "protected_branches" (names)
>    instead of "user_ids" there would be "users" (names)

Is it more work to support/remove the usage of ids? Personally I don't think I would use the ids, but we seem to support that for advanced branch protection settings (i.e. allowed to push, allowed to merge, etc.).

https://gitlabform.github.io/gitlabform/reference/protected_branches/#premium-only-features

So, having ids would make it consistent across gitlabform syntax. That could be useful if someone is modularizing their config using yaml anchors or other setup. Or, maybe the usage of ids in branch protection gets deprecated/removed in v4.

Also, I assume this is being planned for v3. Perhaps we create a separate issue for updating the existing approval rule syntax in v4. For example, instead of the following:

```yaml
      approvers:
        - user1
        - user2
      approver_groups:
        - my-group
        - my-group1/subgroup
        - my-group2/subgroup/subsubgroup
```

This is probably more intuitive and again keeps the overall syntax consistent with other areas of gitlabform (i.e. branch protection, members, etc.)

```yaml
      approvers:
        users:
          - user1
          - user2
        groups:
          - my-group
          - my-group1/subgroup
          - my-group2/subgroup/subsubgroup
```

**Comment by weakcamel** [comment]
I like the proposal for approval rules syntax, it's concise and logical.

It does sound much more convenient to use group/user/branch names instead of IDs, I've not used the IDs so far though to be honest so I don't have an opinion.

**Comment by gdubicki** [comment]
> Is it more work to support/remove the usage of ids? Personally I don't think I would use the ids, but we seem to support that for advanced branch protection settings (i.e. allowed to push, allowed to merge, etc.).
> 
> https://gitlabform.github.io/gitlabform/reference/protected_branches/#premium-only-features
> 
> So, having ids would make it consistent across gitlabform syntax. That could be useful if someone is modularizing their config using yaml anchors or other setup. Or, maybe the usage of ids in branch protection gets deprecated/removed in v4.

Oh, right, we do support both names and ids there. So we can easily do the same here then.

> Also, I assume this is being planned for v3.

Yes, we are talking about adding this to v3.x, probably 3.2.

> Perhaps we create a separate issue for updating the existing approval rule syntax in v4. For example, instead of the following:
> 
> (...)

I am not yet sure about the syntax for v4, but you are right that we should strive for consistency with the areas.

**Comment by gdubicki** [comment]
> It does sound much more convenient to use group/user/branch names instead of IDs, I've not used the IDs so far though to be honest so I don't have an opinion.

It would be optional. F.e. you can use either use a field "group_ids" with numerical ids or a field "groups" with strings with the names (but not both).

**Comment by jimisola** [comment]
I'm not that familiar with merge request approval rules to be honest. We use them but very basic configuration.

I therefore have a few questions:

1. The group id/names, what groups are these? Are this standard groups in GitLab (i.e. that can contain wiki, subgroups, projects etc) or some sort of user group that I've missed?
2. [There seems to be several different levels/types of approval rules](https://docs.gitlab.com/ee/api/merge_request_approvals.html) - project-level and merge request as well as general configuration and project/merge request level rule?
  1. Project-level MR approvals: Change configuration (general) and project-level rule
  1. Merge request-level MR approvals: Change approval configuration (general?) and merge request level rule

Do I understand it correctly that GitLabForm sets the project-level MR approval both change configuration (general) and project-level rule(s)? Ant that, the Merge request-level MR approvals ("_Configuration for approvals on a specific merge request_") is not set by GitLabForm and is normally set by a user in GUI when the user wants to change approval rules for a indeed _specific individual_ MR?

I've read all comments and agree with what you have come up with so far, i.e.

1. @gdubicki's syntax proposal
2. @weakcamel input on supporting both names and ids
4. @weakcamel input a separate issue for updating the existing approval rule syntax (can you create the and add and link it to #331 and the corresponding wiki page?)

**Comment by weakcamel** [comment]
We've been doing some Gitlab housekeeping and reorg within my team and as it turned out, we are now very interested in having the feature of multiple approval rules (and being able to name them instead of the generic "Configured with Gitlabform" rule name).

I'm not sure I'm familiar enough with code base and inner workings of Gitlabform to contribute it as a PR, but if there's some way I could help - e.g. with testing or something else - I'll be happy to.

**Comment by gdubicki** [comment]
Thanks @weakcamel! I plan to implement this feature over the next few weeks and will release a RC version and I will appreciate testing it. :)

**Comment by gdubicki** [comment]
What @zanella is tackling in #423 made me realize that from the implementation point of view it would be easier to treat managing Merge Requests approvals split into:

* approvals settings - with a `SingleEntityProcessor`,
* approval rules - with a `MultipleEntitiesProcessor`,

The simplest way to do it would be to change the new syntax to this (note that `merge_requests_approvals` and `merge_requests_approval_rules` are new sections just below `group/project`):
```yaml
    merge_requests_approvals:
      # (no changes here)
      reset_approvals_on_push: false
      disable_overriding_approvers_per_merge_request: true
      merge_requests_author_approval: false
    merge_requests_approval_rules:
      standard:
        approvals_required: 2
        name: "Regular approvers"
        groups:
          - developers
      security:
        approvals_required: 2
        name: "Extra Security Team approval for selected branches"
        users:
          - secmember1
          - secmember2
        protected_branches:
          - sensitive-branch 
      enforce: true 
```

**Comment by gdubicki** [comment]
Please try out [v3.4.0rc1](https://github.com/gitlabform/gitlabform/releases/tag/v3.4.0rc1) with this feature and a syntax working like described above, @weakcamel. Let me know what you think!

**Comment by Siythrun** [comment]
When running if i have 

```yaml
projects_and_groups:
  "*":
    merge_requests_approval_rules:
      standard:
        approvals_required: 1
        name: "All eligible users"
      enforce: true 

  "config/kustomize/*":
    merge_requests_approval_rules:
      dev-uat:
        approvals_required: 1
        name: "Dev Code Review - UAT"
        groups:
          - developers
          - insights
        protected_branches:
          - uat
      devops-uat:
        approvals_required: 1
        name: "DevOps Code Review - UAT"
        groups:
          - devops
        protected_branches:
          - uat
      inf-pp:
        approvals_required: 1
        name: "Inf/DevOps Approval - PP"
        groups:
          - devops
          - infrastructure
        protected_branches:
          - pp
      inf-prod:
        approvals_required: 1
        name: "Inf/DevOps Approval - Prod"
        groups:
          - devops
          - infrastructure
        protected_branches:
          - prod
      enforce: true
```
The rules are created but non of the groups have been added

![image](https://user-images.githubusercontent.com/7693019/201799170-f4ff5323-a185-43a0-933c-ff5982f64cc6.png)


but removing the merge_requests_approval_rules from the top level into the sub-level it works fine

**Comment by weakcamel** [comment]
For me - so far, so good. A fairly basic scenario works fine:

```
$ gitlabform  --config config_multiple.yml ALL_DEFINED
🏗 GitLabForm version: 3.4.0rc1 = pre-release 🤩 (the latest stable is 3.3.0)
>>> Getting all groups and projects defined in the configuration...
:: # of groups to process: 0
:: (# of omitted groups - empty effective config: 1)
:: # of projects to process: 2
* (1/2) Processing project: very-silly-test-group-for-ldap-and-fun/test-project-2
* (2/2) Processing project: very-silly-test-group-for-ldap-and-fun/testy-project
:: # of groups processed successfully: 0
:: # of projects processed successfully: 2
:: All requested groups/projects processed successfully! ✨
```

Config:
```yaml
---
config_version: 3
gitlab:

projects_and_groups:
  #
  # COMMON settings, applicable to all projects
  #
  '*':
    merge_requests_approvals:
      reset_approvals_on_push: false
      merge_requests_author_approval: true
      disable_overriding_approvers_per_merge_request: true
    merge_requests_approval_rules:
      enforce: true
      all_users:
        approvals_required: 1
        name: Approval by anyone in Engineering
        groups:
          - 'teams/engineering'

  'very-silly-test-group-for-ldap-and-fun/*':
    merge_requests_approvals:
      disable_overriding_approvers_per_merge_request: false
    merge_requests_approval_rules:
      owners:
        name: Approval by Cloud Team
        approvals_required: 1
        groups:
          - 'teams/cloud'
      enforce: true
  'very-silly-test-group-for-ldap-and-fun/testy-project':
    merge_requests_approvals:
      reset_approvals_on_push: true
      merge_requests_author_approval: false
      disable_overriding_approvers_per_merge_request: true
    merge_requests_approval_rules:
      others:
        name: Approval by SRE Team
        approvals_required: 1
        groups:
          - 'teams/sre'
      enforce: true
```

I'm going to fiddle a bit more with more complex combinations of enforce/inherit as well as the scenario mentioned in this issue in the first place ("Any eligible user")

**Comment by weakcamel** [comment]
As for the "Any eligible user" rule, I might be using it wrong or something's going on:


* Using just `merge_requests_approvals.approvals_required` had no effect and was ignored; built-in rule was reset to "Any eligible user" but number of required approvals was 0
* Adding the `approvals_before_merge` value resulted in a failure

The config I used:

```
$ gitlabform  --config config_reset.yml ALL_DEFINED
🏗 GitLabForm version: 3.4.0rc1 = pre-release 🤩 (the latest stable is 3.3.0)
>>> Getting all groups and projects defined in the configuration...
:: # of groups to process: 0
:: (# of omitted groups - empty effective config: 1)
:: # of projects to process: 2
* (1/2) Processing project: very-silly-test-group-for-ldap-and-fun/test-project-2
Error: Setting the 'approvals_before_merge' in the 'merge_requests_approvals' sections is not allowed as it is not clear which rule does it apply to. Please set it inside the specific approval rules in the 'merge_requests_approval_rules' section.
```


The config I used:

```yaml
---
config_version: 3
gitlab:

projects_and_groups:
  #
  # COMMON settings, applicable to all projects
  #
  '*':
    merge_requests_approvals:
      reset_approvals_on_push: false
      merge_requests_author_approval: true
      disable_overriding_approvers_per_merge_request: true
    merge_requests_approval_rules:
      enforce: true
      all_users:
        approvals_required: 1
        name: Approval by anyone in Engineering
        groups:
          - 'teams/engineering'

  'very-silly-test-group-for-ldap-and-fun/*':
    merge_requests_approvals:
      disable_overriding_approvers_per_merge_request: false
    merge_requests_approval_rules:
      owners:
        name: Approval by Cloud Team
        approvals_required: 1
        groups:
          - 'teams/cloud'
      enforce: true
  'very-silly-test-group-for-ldap-and-fun/test-project-2':
    merge_requests_approvals:
      approvals_required: 1
      approvals_before_merge: 1
    merge_requests_approval_rules:
      inherit: false
      enforce: true
```

**Comment by weakcamel** [comment]
Hang on :) I re-visited [this comment](https://github.com/gitlabform/gitlabform/issues/388#issuecomment-1237280160) and tried that recipe.

That worked!

```
  ...
  'very-silly-test-group-for-ldap-and-fun/test-project-2':
    merge_requests_approval_rules:
      inherit: false
      enforce: true
      default:
        approvals_required: 1
        name: "All Members"
        rule_type: any_approver
```

One tiny cosmetic thing is, `name` doesn't really apply for such a rule, so UI won't be showing `All Members` anywhere. I don't think that's a problem, merely an observation.
