### ISSUE TITLE
Add creation of groups and projects

### ISSUE THREAD

**Issue by gdubicki** [gitlabform/gitlabform#399]
I have been told by one person that they would use this app if it could automatically create groups and projects.

(This is also the last remaining unimplemented feature mentioned in #6.)

**Comment by weakcamel** [comment]
For me this is not a dealbreaker at all (apparently!), but it would be a nice thing to have, especially for "access" groups (we currently manage project/group access by sharing with project-less groups, e.g. "foo-team", "bar-team" which emulates a role-based access control).

**Comment by amimas** [comment]
Same here.. What @weakcamel  said.

It's not a deal breaker for me because we don't expect to create random projects on a daily or hourly basis. We also created a subgroup where everyone has access to create random projects for their POC. Have a more relaxed config for that subgroup being managed by gitlabform.

I'm also using separate project-less groups as @weakcamel  mentioned. It helps with finer codeowner, approval, etc.

**Comment by kriko** [comment]
Would really-really appretiate this functionality as well!

Looking to implement GitLabForm, to roll out and deploy preconfigured GitLab (sub)groups and projects for a GitOps solution, however the only current limitation seems to be the unability to create groups and projects. Wouldn't want to use the Terraform solution or custom API calls to solve this.

Looking at the code, it seems that both the Groups API ([create_group method](https://github.com/gitlabform/gitlabform/blob/main/gitlabform/gitlab/groups.py#L33)) and Projects API implementations ([create_project method](https://github.com/gitlabform/gitlabform/blob/main/gitlabform/gitlab/projects.py#L29)) fully support the creation of these, but it has not yet been implemented. I could try to make a patch for it, but not sure, if I'd be able to follow the current coding practice and design.

As per configuration goes and since the current definition of GitLab path type objects (groups, subgroups, projects) simply states that each group and project are explicitly defined (we don't have group settings that apply to sub-groups of that group), then it would be easy:

Objects (groups/projects) are created based on their order of appearance (or perhaps it's a good idea to sort them before handling, to get the order of creation correct), thus root groups can be created first, then their subgroups and finally projects nested underneath.

A configuration tag would enable backwards compatible behaviour, so "create_if_not_found: true" would enable the creation of the objects.

Otherwise, having gone through the GitLab API v4 definition for both Groups and Projects, very little is different between creation and update requests, with the exception of a few fields, from my research:

### Groups API - group creation
```
    name: "" # Type: string # Required: yes # The name of the group.
    path: "" # Type: string # Required: yes # The path of the group.
    parent_id: # Type: integer # Required: no # The parent group ID for creating nested group.
```
For the creation of subgroups, parent_id is required, however it might not be known, it the parent also has to be created, thus we could implement a lookup for the parent which should be derived from the definition, eg. `root-group/child-group` that would then be used as a lookup to get the ID of the parent.
`parent_id` is not supported for update requests.

### Projects API - create project configuration
```
    name: ""         # string  # Required: Yes # if path isn’t provided) The name of the new project. Equals path if not provided.
    path: ""         # string  # Required: Yes # if name isn’t provided) Repository name for new project. Generated based on name if not provided (generated as lowercase with dashes). Starting with GitLab 14.9, path must not start or end with a special character and must not contain consecutive special characters.
    namespace_id: "" # integer # Required: No  # Namespace for the new project (defaults to the current user’s namespace).
```
Again, similarily, namespace_id is the ID of the group where this project belongs under, a similar lookup is required as for groups.
`namespace_id` is not supported for update requests.

### Potential configuration
Thus the example configuration could look as follows:
```
projects_and_groups:

  root-group/*:
    create_if_not_found: false # backwards compatible behaviour, false is default
    group_settings:
      name: "Root Group"
      description: "Should not be created when doesn't exist."

  root-group/root-project:
    create_if_not_found: true
    project_settings:
        name: "Project 1"
        description: "This project will be created under root-group."

  root-group/project-dontcreate:
    create_if_not_found: false
    project_settings:
        name: "Project 1"
        description: "This project will not be created, only updated if it exists."

  root-group/child-group/*:
    create_if_not_found: true
    group_settings:
      name: "Child of root group"
      description: "This group will be created under root-group, when it doesn't exist"

  root-group/child-group/grandchild-group/*:
    create_if_not_found: true
    group_settings:
      name: "Grandchild group"
      description: "This group will be created under child-group, when it doesn't exist"

  root-group/child-group/grandchild-group/grandchild-project:
    create_if_not_found: true
    project_settings:
        name: "Project of grandchild-group"
        description: "Will be created under grandchild-group when the group has been created."
```

What do others think?
@amimas

**Comment by amimas** [comment]
Thanks for the config suggestions @kriko . Let's talk about project creation, since I think that's probably easier to decide :)

For project level configs, I still suggest we should add the `create_if_not_found` under the `project` map. See [this comment](https://github.com/gitlabform/gitlabform/issues/399#issuecomment-1652190852)

```yaml
projects_and_groups:
  group_1/project_1:
    project:
      create_if_not_found: true
    project_settings:
        name: "Project 1"
        description: "This project will be created under root-group."
```

Currently, gitlabform processes `project` first and then takes care of `project_settings`. So, the above will create a project using `project_1` as the both `name` and `path`. And it will be created under `group_1` namespace. When `project_settings` is being processed, it can change the name to `Project 1`.

Going with the above pattern, maybe we should introduce a `group` key and that one should contain the `create_if_not_found` key. It might start facilitating other features just like certain features are handled via `project` config.

> Objects (groups/projects) are created based on their order of appearance (or perhaps it's a good idea to sort them before handling, to get the order of creation correct), thus root groups can be created first, then their subgroups and finally projects nested underneath.

Looking at issue #105 and the discussions in there so far, it might not be as straight-forward. For that issue, I think sorting will need to be done in reversed order than what you're proposing.

I think group creation might be a bit challenging because of the above processing order issue. It might require more discussions and thoughts. Adding support for project creation will probably be faster and easier.

@gdubicki, @jimisola - any thoughts?

**Comment by gdubicki** [comment]
Hi everyone!

I completely agree with you, @amimas. Just a note: if we make `ProjectProcessor` and - a newly created - `GroupProcessor` special in a way that they need to run first, let's make it explicit in the code, _at least_ with an appropriate comment.

As for the groups and the ordering problem:
* we currently process [groups before projects](https://github.com/gitlabform/gitlabform/blob/76910144c8ca61c266c782547c07b3aa90cadd84/gitlabform/__init__.py#L355-L500) - so we have a problem that a group needs to exist to create a project in it covered,
* we process the groups in [the order of their sorted paths](https://github.com/gitlabform/gitlabform/blob/76910144c8ca61c266c782547c07b3aa90cadd84/gitlabform/lists/__init__.py#L51-L51), which gives us higher-level groups before their subgroups - so we also have a problem that a higher-level group has to exist to create a subgroup in it covered too.

...so I am under impression that from the point of view of this issue we don't have any problem with ordering. Please correct me if I am wrong.

**Comment by gdubicki** [comment]
While I like the idea to put project/group creation in their "first" processors (this keeps the config structure intact), it creates a problem that we wouldn't have if the creation would happen "when needed", like in the current https://github.com/gitlabform/gitlabform/pull/708.

So the problem is that if we put the new flags in the common configuration level, omit a definition of some parent entity "A" but **do** refer to an entity "B" to create in that entity "A", the run will fail.

For example this config:
```yaml
projects_and_groups:
  *:
    project:
      create_if_not_found: true
    group:
      create_if_not_found: true
  new_group/new_project:
    project_settings:
      default_branch: foobar
```
...will generate an error as the group new_group was not mentioned in the config explicitly.

However we could prevent this problem by adding to the lists of projects and groups returned by `ProjectsProvider` and `GroupsProvider`, the projects and groups/subgroups mentioned in the config.

Note that they should be added also when we run gitlabform for "ALL", as it's not enough to take even all the existing projects and groups from GitLab instance, if we may also need to create new ones from the config.

Also note that if we reference a subgroup in the config or a project in a subgroup, we should add both the subgroup **and** its parent group to the list of groups (and do this recursively).
