### ISSUE TITLE
automatically cleanup other group_ldap_links

### ISSUE THREAD

**Issue by trissanen** [gitlabform/gitlabform#403]
Hi,

I'd like to be able to set group_ldap_links for a group definitely so that when I run gitlabform, it would also delete other previous ldap syncs for the project in a similar way like when you set enforce: true for members.

I haven't found a way to do this yet, not sure if such a flag already exists, but at least it's not documented

```
  mygroup/subgroup/*:
    group_ldap_links:
      enforce: true
      some_ldap_thing:
        provider: ldapmain
        cn: My_Group
        group_access: maintainer
```
