### ISSUE TITLE
Subgroup badges how-to

### ISSUE THREAD

**Issue by guilhem-martin** [gitlabform/gitlabform#434]
Hello,

I've been using project badges:

 ```yml
'my_group/my_project':
    badges:
      my_badge
        name: "My Badge"
        link_url: "https://linkurl"
        image_url: "https://imageurl"
```
as well as root group badge, to create the group badge, so that any project or subgroup within the group inherits from it:

```yml
'*':
   group_badges:
     group-pipeline-status:
       name: "Pipeline status"
       link_url: "https://linkurl"
       image_url: "https://imageurl"
```
I've also apply project badges to multiple projects using wildcard *. All of this working fine!

Now, I don't get the syntax needed for applying a group badge to a subgroup.
I've tried:

```yml
   'rootgroup/subgroup/*':
      group_badges:
        group-mybadge:
          name: "Should be a Group badge of the subgroup"
          link_url: "https://linkurl"
          image_url: "https://imageurl"
```
with and without the wildcard, but the badge is not applied.

Any hint on what I'm missing here?
Thanks.

**Comment by gdubicki** [comment]
Hi @guilhem-martin!

Thanks for reporting the issue.

What are the parameters you are running GitLabForm with? Are you pointing to a specific group or use `ALL` or `ALL_DEFINED`?

I want to make sure if it's generating the list of entities to work on is buggy/missing features or if the problem is in generating the effective config for your subgroup.

**Comment by gdubicki** [comment]
I did some tests on my machine and it seems that when you run GitLabForm with the `target` argument set to:
* `ALL_DEFINED` then the `rootgroup/subgroup` IS included and the config is applied. I didn't test that but I am sure that it works the same way for `ALL`.
* `rootgroup/subgroup` then the _only_ entity that the config is applied is that subgroup and it works too.
* `rootgroup` then the subgroup is NOT included in the effective entities lists - only the subprojects are included. I didn't expect that...

**Comment by guilhem-martin** [comment]
@gdubicki thanks a bunch for the feedback.
I'm left without my PC, but I think I'm in the third situation you describe. I'll confirm this.

**Comment by guilhem-martin** [comment]
Hello @gdubicki 
back to my PC. 
My configuration is like your third bullet point with target set to `rootgroup` - explaining the behavior I'm encountering.

**Comment by amimas** [comment]
Curious what happens if it's set to `rootgroup/*`

**Comment by gdubicki** [comment]
> Curious what happens if it's set to `rootgroup/*`

It doesn't work.:

```
>>> Getting requested groups or projects...
Error: Project or group rootgroup/* cannot be found in GitLab!
```

And I don't feel great with this as it feels like an inconsistency..

**Comment by amimas** [comment]
Thanks for clarifying.

I always use `ALL DEFINED` when executing gitlabform. And I use different config file for different groups. It might not help, but thought I'd mention in case it works as a workaround.

One benefit is that i can run gitlabform in parallel in the CI to take care of different groups and their projects.

**Comment by gdubicki** [comment]
> Hello @gdubicki
> back to my PC.
> My configuration is like your third bullet point with target set to `rootgroup` - explaining the behavior I'm encountering.

Thanks.

I've been thinking about it and my proposal is to treat this as a bug and fix it to make query like `rootgroup` include the given group's subgroups recursively. I am just slightly worried that [this will break someone's workflow](https://xkcd.com/1172/) if we do this in a minor or patch release..

**Comment by guilhem-martin** [comment]
Hello @gdubicki 

loved the xkcd reference :)

I've tried a setup using `ALL_DEFINED` as target.
First of all, here is a representation of my test group & subgroup:

```
gitlabform/
├── gitlabformmgr
├── subgroup/
│   ├── Project of subgroup
│   └── subsubgroup/
│       └── Project of subsubgroup
```

My gitlabform.yml looks as following:

```yml
projects_and_groups:
   'gitlabform/*':
      group_badges:
        group-pipeline-status:
          name: "gitlabform/* Pipeline status"
          link_url: "https://my-url/%{project_path}/-/commits/%{default_branch}"
          image_url: "https://my-url/%{project_path}/badges/%{default_branch}/pipeline.svg"

   'gitlabform/subgroup/*':
      group_badges:
        group-opensource:
          name: "gitlabform/subgroup/* opensource"
          link_url: "https://my-url"
          image_url: "https://my-url/badge/%{project_id}?path=%{project_path}"

   'gitlabform/gitlabformmgr':
     badges:
       opensource:
         name: "gitlabform/gitlabformmgr opensource"
         link_url: "https://my-url"
         image_url: "https://my-url/badge/%{project_id}?path=%{project_path}"
 ```

My expected outcome is:

```
gitlabform/ 🢂 Has the badge "gitlabform/* Pipeline status"
├── gitlabformmgr 🢂 Has the badge "gitlabform/gitlabformmgr opensource"
├── subgroup/ 🢂 Has the badge "gitlabform/subgroup/* opensource"
│   ├── Project of subgroup
│   └── subsubgroup/
│       └── Project of subsubgroup
```

What I get in reality is the following:

```
gitlabform/ 🢂 Has the badge "gitlabform/* Pipeline status"
├── gitlabformmgr 🢂 Has the badge "gitlabform/gitlabformmgr opensource"
├── subgroup/ 🢂 Has the badge "gitlabform/subgroup/* opensource" AND has also the badge ""gitlabform/* Pipeline status"
│   ├── Project of subgroup
│   └── subsubgroup/
│       └── Project of subsubgroup
```

As a consequence, the "Project of subgroup" has 3 badges in total:
- opensource (that's OK)
- Pipeline status from root level "gitlabform" (that's OK)
- Pipeline status of subgroup (I thought it would not be there)

So the project of subgroup (same with the project of subsubgroup) has 2 identical badges "Pipeline Status".

![image](https://user-images.githubusercontent.com/226993/202298669-36c27bb8-a456-4b58-b412-59a701eb6dd8.png)

Do you know if I can set-up things in order to have the group badge "gitlabform/* Pipeline status" only applying to group "gitlabform" and not to its descendant?

Thanks,

Guilhem.

**Comment by gdubicki** [comment]
The behaviour you observe is expected. If you have a group `gitlabform/*` and define `group_badges` for it then this is inherited by all the subgroups in this group. See https://gitlabform.github.io/gitlabform/reference/#configuration-hierarchy.

You can deal with that in 2 ways:

* overwrite the badge in a subgroup by using the the same label as in the group, because the effective config is a merge of the group and subgroup configs (see https://gitlabform.github.io/gitlabform/reference/#effective-configuration):

```yaml
projects_and_groups:
   'gitlabform/*':
      group_badges:
        group-pipeline-status:
          name: "gitlabform/* Pipeline status"
          link_url: "https://my-url/%{project_path}/-/commits/%{default_branch}"
          image_url: "https://my-url/%{project_path}/badges/%{default_branch}/pipeline.svg"

   'gitlabform/subgroup/*':
      group_badges:
        group-pipeline-status: # the same name as above, but different values below
          name: "gitlabform/subgroup/* opensource"
          link_url: "https://my-url"
          image_url: "https://my-url/badge/%{project_id}?path=%{project_path}"
```

* disable inserting config in the subgroup - see https://gitlabform.github.io/gitlabform/reference/#breaking-inheritance for more info:

```yaml
projects_and_groups:
   'gitlabform/*':
      group_badges:
        group-pipeline-status:
          name: "gitlabform/* Pipeline status"
          link_url: "https://my-url/%{project_path}/-/commits/%{default_branch}"
          image_url: "https://my-url/%{project_path}/badges/%{default_branch}/pipeline.svg"

   'gitlabform/subgroup/*':
      group_badges:
        inherit: false # this key will case 'gitlabform/*'. group_badges config to NOT be inherited here
        group-opensource:
          name: "gitlabform/subgroup/* opensource"
          link_url: "https://my-url"
          image_url: "https://my-url/badge/%{project_id}?path=%{project_path}"
```

(I am skipping the project-level config here as it works independently and as expected. But of course you need it to to get your expected results. :)
