### ISSUE TITLE
Branch config doesn't merge specific config with common config

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#444]
**Describe the bug**

Not sure if it's a bug or not but feels like it's a bug. Also, please feel free to edit the Title if you think it can be described better.

In my gitlabform config, I have a common config and a project specific config section as shown below. I'm excluding other settings to minimize the noise.

```yaml
config_version: 2

projects_and_groups:
  # Default settings for ALL projects in group1
  group1/*:
    branches:
      main:
        protected: true
        unprotect_access_level: maintainer
        push_access_level: no access
        merge_access_level: developer
        code_owner_approval_required: true

  group1/project1:
    project_settings:
      description: |
        Description of this project.
      topics:
        - label1
        - label2
```

So far this has been working fine. The branch protection config is applied successfully to `project1` taken from the common config.

I needed to make a small tweak to the branch protection for `project1`. Needed to change the merge access. So, I made the following changes:

```diff
config_version: 2

projects_and_groups:
  # Settings for ALL projects in group1 group and the group itself
  group1/*:
    branches:
      main:
        protected: true
        unprotect_access_level: maintainer
        push_access_level: no access
        merge_access_level: developer
        code_owner_approval_required: true

  group1/project1:
    project_settings:
      description: |
        Description of this project.
      topics:
        - label1
        - label2
+      branches:
+        main:
+          merge_access_level: no access
+          allowed_to_merge:
+            - group: group-users-ops
 ```

This didn't seem to work. After gitlabform ran, the `main` branch protection setting of `group1/project1` wasn't updated. Looking at the effective config generated by gitlabform, it seems the changes made to the `branches` key under `group1/project1` didn't get merged with common config. It looks like this:

```yaml
group1/project1:
  project_settings:
    description: |
      Description of this project.
    topics:
      - label1
      - label2
  branches:
    main:
      merge_access_level: 0
      allowed_to_merge:
      - group: group-users-ops
```

If I re-define the entire config of `main` branch in `group1/project1`, then I believe it'll work fine.

**GitLabForm version**

```
🏗  GitLabForm version: 2.11.1 = outdated 😔, please update! (the latest stable is 3.3.1)
```

**GitLab version**

`15.2.2-ee`
