### ISSUE TITLE
Group settings are not applied to sub-groups

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#446]
Not sure if this is a bug or a feature request. I need to create couple of new subgroups and it seems I have to repeat some configs for them to be applied to the subgroup. Here I'm referring to "group settings" only.

Sample config:

```yaml
config_version: 2

projects_and_groups:
  group1/sub-group1/*:
    group_settings:
      description: <description of the "sub-group1">
      project_creation_level: maintainer
      subgroup_creation_level: owner
      visibility: internal
      mentions_disabled: true
      request_access_enabled: false

    project_settings:
      # Settings of ALL projects
      visibility: internal
      description: This is test

  group1/sub-group1/sub-sub-group1/*:
    group_settings:
      description: Projects for xyz

  group1/sub-group1/sub-sub-group2/*:
    group_settings:
     description: Projects for abc.
```

With this above config, settings specified under `group_settings` of `group1/sub-group1/*` didn't get applied to the 2 nested subgroups. But, the `project_settings` of `group1/sub-group1/*` is applied to all projects under the 2 nested sub-groups (i.e. `group1/sub-group/sub-sub-group1`).

Perhaps `group_settings` should be applied to the sub-groups also unless any specific setting is being overwritten? In my case, I have to repeat some of the configs like this:

```yaml
  group1/sub-group1/*:
    group_settings:
      description: <description of the "sub-group1">
      project_creation_level: maintainer
      subgroup_creation_level: owner
      visibility: internal
      mentions_disabled: true
      request_access_enabled: false

  group1/sub-group1/sub-sub-group1/*:
    group_settings:
      description: Projects for xyz
      project_creation_level: maintainer
      subgroup_creation_level: owner
      visibility: internal
      mentions_disabled: true
      request_access_enabled: false

  group1/sub-group1/sub-sub-group2/*:
    group_settings:
     description: Projects for abc.
      project_creation_level: maintainer
      subgroup_creation_level: owner
      visibility: internal
      mentions_disabled: true
      request_access_enabled: false
```

If we agree with it, I suppose this will have to released as a breaking change.
