### ISSUE TITLE
files with `file: <my-relative-file-path>` always returns exception

### ISSUE THREAD

**Issue by anb0s** [gitlabform/gitlabform#447]
**Describe the bug**

I'm trying copy of some files from repo running GitLabForm job:

```
config_version: 3

gitlab:
  url: https://<own-ce-gitlab>

projects_and_groups:
  "*":
    files:
      "LICENSE.md":
        file:
          - "LICENSE.md"
        branches:
          - "main"
        commit_message: "chore(license): add LICENSE.md according to with SISL 1.4"
        overwrite: false
```

facing exception:
```
Processing section 'files'
Processing file 'LICENSE.md' in branch 'main'
Warning: Error occurred while processing project reusable-ci/templates/fork-me, exception:
[Errno 2] No such file or directory: "['LICENSE.md']"
```

**GitLabForm version**

3.3.1

**GitLab version**

15.6.0

**Comment by anb0s** [comment]
ah sorry just realized the issue, i've used array 🤭 now it works, great extension 👍 

```
config_version: 3

gitlab:
  url: https://<own-ce-gitlab>

projects_and_groups:
  "*":
    files:
      "LICENSE.md":
        file: "assets/LICENSE.md"
        branches:
          - "main"
        commit_message: "chore(license): add LICENSE.md according to with SISL 1.4"
        overwrite: false
```
