### ISSUE TITLE
support file patterns

### ISSUE THREAD

**Issue by anb0s** [gitlabform/gitlabform#448]
The [files section](https://gitlabform.github.io/gitlabform/reference/files/) should support file patterns and target path.

instead of listing two files that are in path `assets/*`
```
projects_and_groups:
  "*":
    files:
      "LICENSE.md":
        file: "assets/LICENSE.md"
        branches:
          - "main"
        commit_message: "chore(license): add LICENSE.md according to with SISL 1.4"
        overwrite: false
      "COPYING.md":
        file: "assets/COPYING.md"
        branches:
          - "main"
        commit_message: "chore(license): add COPYING.md according to with SISL 1.4"
        overwrite: false
```

we could define target pattern (or just path?) as `*.md` or `./*` and allow source pattern in file, e.g. `file: "assets/*.md"`
```
projects_and_groups:
  "*":
    files:
      "*.md":
        file: "assets/*.md"
        branches:
          - "main"
        commit_message: "chore(license): add license files according to with SISL 1.4"
        overwrite: false
```

So it would be easier to apply common files.

**Comment by gdubicki** [comment]
Hi @anb0s!

Thank for the suggestion.

I have doubts about putting a pattern into the key like `*.md`. This could be interpreted as managing all .md files in the root dir of the repo with this config while you probably wanted to only manage the files found in `assets/*.md`.

However I also noticed that it would be good to improve the syntax of this section. In our gitlabform config we have this for a group of project with our custom Puppet modules:

```yaml
      files:
        .gitlab-ci.yml:
          overwrite: true
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/.gitlab-ci.yml
        .gitlab-ci.per_module.yml:
          overwrite: false # this file by design should be overwritten in each module with custom tests
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/.gitlab-ci.per_module.yml
        .yamllint:
          overwrite: true
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/.yamllint
        deploy_module_to_puppetmaster.sh:
          overwrite: true
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/deploy_module_to_puppetmaster.sh
        Rakefile:
          overwrite: true
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/Rakefile
        Gemfile:
          overwrite: true
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/Gemfile
        .gitattributes:
          overwrite: false # if this file is already in any module then it's probably better / more custom than this one
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/.gitattributes
        spec/spec_helper.rb:
          overwrite: false # if this file is already in any module then it's probably better / more custom than this one
          branches:
            - develop
            - master
          only_first_branch: true
        config/modules/spec/spec_helper.rb
          file: config/modules/spec/spec.opts
          overwrite: false # if this file is already in any module then it's probably better / more custom than this one
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/spec/spec_helper.rb
       spec/classes/init_spec.rb:
          overwrite: false # if this file is already in any module then it's probably better / more custom than this one
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/spec/classes/init_spec.rb
       .fixtures.yml:
          overwrite: false # if this file is already in any module then it's probably better / more custom than this one
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/.fixtures.yml
        metadata.json:
          overwrite: false # if this file is already in any module then it's probably better / more custom than this one
          branches:
            - develop
            - master
          only_first_branch: true
          file: config/modules/metadata.json
```

There's a lot of duplication here. So I can imagine shortening this to 2 groups of files:

```yaml
      files:
        overwrite: # just a label here
          overwrite: true
          branches:
            - develop
            - master
          only_first_branch: true
          files: # mapping from local file to a repository file
            config/modules/.gitlab-ci.yml: .gitlab-ci.yml
            config/modules/.gitlab-ci.per_module.yml: .gitlab-ci.per_module.yml
            config/modules/.yamllint: .yamllint
            config/modules/deploy_module_to_puppetmaster.sh: deploy_module_to_puppetmaster.sh
            config/modules/Rakefile: Rakefile
            config/modules/Gemfile: Gemfile
        dont_overwrite: # just a label here
          overwrite: false # if this file is already in any module then it's probably better / more custom than this one
          branches:
            - develop
            - master
          only_first_branch: true
          files: # mapping from local file to a repository file
            config/modules/.gitattributes: .gitattributes
            config/modules/spec/spec.opts: spec/spec.opts
            config/modules/spec/spec_helper.rb: spec/spec_helper.rb
            config/modules/spec/classes/init_spec.rb: spec/classes/init_spec.rb
            config/modules/.fixtures.yml: .fixtures.yml
            config/modules/metadata.json: metadata.json
```

Please note that I just wanted to think about it a bit and discuss it but I don't promise I will take up implementing this improvement.

**Comment by anb0s** [comment]
@gdubicki thanks for discussion :) i like your proposal, it will reduce the duplicates and with this syntax it also creates only one commit (message) that i wanted to request next ;)

A pattern approach is maybe also valid, e.g. move all related files is assets subfolder and then have only this rule:
```
projects_and_groups:
  "*":
    files:
      license_files: # just a label
        files:
          assets/license/*.md: *.md
        branches:
          - "main"
        commit_message: "chore(license): add license files according to with SISL 1.4"
        overwrite: false
```
Benefit would be to not touch this config anymore, just place new files to subfolder and run job...


About contributing: yes sure i understand, I'm new to this library and will need some time to understand how to implement this in the code base...
