### ISSUE TITLE
files: configure branch name via CLI or environment variable

### ISSUE THREAD

**Issue by anb0s** [gitlabform/gitlabform#453]
For file actions it would be good to support variables / defines passed via CLI, e.g. `gitlabform --define/-D <NAME=VALUE>`.

So if user of CI job passes own (MR) branch name to apply files to and then review and merge, instead of using fixed branch like `main` that may have full protection `push_access_level: no access`

`.gitlab-ci.yml`:
```
variables:
  BRANCH_NAME:
    value: "main"
    description: "Set the existing branch name to apply file templates, ATTENTION main branch is protected -> disable protection first!"
...
.form:
  script: gitlabform -D "branch=$BRANCH_NAME" $PROJECT_PATH
```

 `config.yml`
```
projects_and_groups:
  "*":
    branches:
    files:
      "README.md":
        file: "assets/README.md"
        branches:
          - "{{ branch }}"
        commit_message: "chore(contributing): add README.md for contributing"
        overwrite: false
      "CONTRIBUTING.md":
        file: "assets/CONTRIBUTING.md"
        branches:
          - "{{ branch }}"
        commit_message: "chore(contributing): add CONTRIBUTING.md for contributing"
        overwrite: false
```

I know branch creation is not implemented, would make sense to add it later and to have option for creating branch if does not exists...

**Comment by gdubicki** [comment]
Thanks for the suggestion @anb0s!

...but I think I don't understand what you are trying to achieve. Can you elaborate please?

**Comment by anb0s** [comment]
OK  :) I'm trying to use one `config.yml` with `files` sections but variable branch name `{{ branch }}`, because user or script should define the branch name that is used to commit files. I do not want to hardcode the branch name, e.g. to `main`, because usually it's protected. The variable branch name can be created before e.g. `chore/update_files_to_v1.0` and used  after gitlabform for a MR to be reviewed and then merged manually to main.

I hope it makes sense now...

**Comment by gdubicki** [comment]
But GitLabForm has built-in code to deal with managing files in protected branches. The app should unprotect the branch, update the files and protect the branch back to how it was before. Doesn't this work for you?

**Comment by anb0s** [comment]
ok, i did not expected this magic ;) i will try...

Anyway some (jinja like) preprocessing is still valid to pass `-D key=value` from script / CI for branches or also forsing overwrite `{{ overwrite }}`

```
projects_and_groups:
  "*":
    branches:
    files:
      "README.md":
        file: "assets/README.md"
        branches:
          - "{{ branch }}"
        commit_message: "chore(contributing): add README.md for contributing"
        overwrite: {{ overwrite }}
      "CONTRIBUTING.md":
        file: "assets/CONTRIBUTING.md"
        branches:
          - "{{ branch }}"
        commit_message: "chore(contributing): add CONTRIBUTING.md for contributing"
        overwrite: {{ overwrite }} 
```

I have solved this now via own jinja2 call that generates the real `config.yml` from such parameters... have tio think about it again ...

**Comment by anb0s** [comment]
@gdubicki  ok i remember that it did not worked for me, now reproduced and with `files` facing this error message:
```
Processing file 'CHECKLIST.md' in branch 'main'
Error: Operation add on file CHECKLIST.md in branch main not permitted, but we don't have a branch protection configuration provided for this branch. Breaking as we cannot unprotect the branch as we would not know how to protect it again. 1
```

```
config_version: 3

gitlab:
  url: <gitlaburl>

projects_and_groups:
  "*":
    files:
      "LICENSE.md":
        file: "assets/LICENSE.md"
        branches:
          - "main"
        commit_message: "chore(license): add LICENSE.md according to SISL"
        overwrite: false
      "COPYING.md":
        file: "assets/COPYING.md"
        branches:
          - "main"
        commit_message: "chore(license): add COPYING.md according to SISL"
        overwrite: false
      "CHECKLIST.md":
        file: "assets/CHECKLIST.md"
        branches:
          - "main"
        commit_message: "chore(license): add CHECKLIST.md according to SISL"
        overwrite: false
```
