### ISSUE TITLE
Member enforcement conflicts with GitLab-generated bots

### ISSUE THREAD

**Issue by lhokktyn** [gitlabform/gitlabform#454]
**Describe the bug**

> NOTE: I'm not sure if this is strictly a _bug_, but it does highlight a potential blocker in terms of using Project Access Tokens

Summary:

Setting `members.enforce: true` throws a 403 if there are project bot users associated with the project, i.e.

```shell
Request url='https://.../group/project/members/123456', method=DELETE, failed - expected code(s) [204, 404], got code 403 & body: '{"message":"403 Forbidden"}'
```

Replicate with:

1. Create a Project Access Token on the project to manage with GitLabForm (which in turn creates a bot user against that project)
2. Run `gitlabform` against that project with a config along the lines of ...

```yaml
config_version: 3

projects_and_groups:
  "path/to/project":
    members:
      users:
        example.real.user:
          access_level: maintainer
      enforce: true
```

**Desired behaviour**

I feel that GitLabForm should either ignore bot users when it comes to the `enforce` option, or allow an alternative option to let the user decide if bots should be ignored or not, e.g.

```yaml
config_version: 3

projects_and_groups:
  "path/to/project":
    members:
      users:
        example.real.user:
          access_level: maintainer
      enforce:
        named_members: true
        bot_members: true
```

**GitLabForm version**

3.3.2

**GitLab version**

`15.7.0-pre dc5804a9a33` (GitLab SaaS)

**Comment by gdubicki** [comment]
Hi @lhokktyn! Thanks for reporting this.

I agree that it would be more convenient to have a flag that would allow ignoring the bot users even when we want to enforce members.

Until this is implemented you can just add those users to the config - this is what we do at Egnyte. Example config:

```yaml
projects_and_groups:
  group_x/project_y:
    members:
      users:
        project_4187_bot:
          access_level: maintainer
      enforce: true
      # we actually manage the people how are members with `group_members:` section
      # that also contains `enforce: true`
```

We are open to reviewing and accepting PRs with this feature but we don't currently plan to implement it ourselves. One note about the syntax: I suggest a separate flag without changing how `enforce: true` works to make it backward compatible. Example:

```yaml
projects_and_groups:
  "path/to/project":
    members:
      users:
        example.real.user:
          access_level: maintainer
      enforce: true
      ignore_bot_members: true
```
