### ISSUE TITLE
Can't manage members of top-level group

### ISSUE THREAD

**Issue by escalate** [gitlabform/gitlabform#466]
**Describe the bug**

I would like to manage the members of our top-level groups.
e.g. /infrastructure
I'm not able to write the correct config.yml for this task.
I have tried several variants.

Variant 1: 
Here the user was only assigned to all subgroups of /infrastructure. However, not to the actual top-level group.
```
config_version: 3

projects_and_groups:
  "infrastructure/*":
    group_members:
      users:
        user1:
          access_level: owner
```

Variant 2:
An error was issued here for a subgroup of /infrastructure.
Error: The inheritance-break flag set in "infrastructure/subgroup" under key "users" is invalid
```
config_version: 3

projects_and_groups:
  "infrastructure/*":
    group_members:
      users:
        inherit: false
        user1:
          access_level: owner
```

Variant 3:
No error was output here. However, no change was made either.
```
config_version: 3

projects_and_groups:
  "infrastructure":
    group_members:
      users:
        user1:
          access_level: owner
```

Could you please help me to find the correct configuration?

**GitLabForm version**

3.4.0rc1

**GitLab version**

14.9.4-ee

**Comment by gdubicki** [comment]
Hi @escalate! Thanks for the detailed question.

Your problem seems to be the opposite of what was asked for in https://github.com/gitlabform/gitlabform/issues/434#issuecomment-1361247072 - there a user wanted to manage some settings *only* for a group, but not it's subgroups, while you want to manage subgroups, but not the group.

Unfortunately this is not yet supported but if we come up with a backward-compatible way to implement it, the chances for getting it added relatively soon are higher.

How about we do this:
```
projects_and_groups:
  "infrastructure": # settings for the "infrastructure" group, but NOT its projects or subgroups
```
and
```
projects_and_groups:
  "infrastructure/**": # settings for the projects and the subgroups of "infrastructure" but NOT that group itself
```
...while keeping the existing:
```
projects_and_groups:
  "infrastructure/*": # settings for the "infrastructure" group AND its subgroups
```
...and...:
projects_and_groups:
  "infrastructure/project": # settings for the "infrastructure/project" project
```

Does this make sense to you? cc @amimas @jimisola

**Comment by escalate** [comment]
Hello @gdubicki ,

thank you for your quick response.
I will wait for this feature.

Best regards
Felix

**Comment by gdubicki** [comment]
Let’s keep this open until we implement it, @escalate :)

**Comment by amimas** [comment]
Hi @gdubicki  - I think the following two samples from your proposal might be conflicting.

```yaml
projects_and_groups:
  "infrastructure": # settings for the "infrastructure" group, but NOT its projects or subgroups
```

```yaml
projects_and_groups:
  "infrastructure/project": # settings for the "infrastructure/project" project
```

Here the second example could be a project or another specific subgroup of `infrastructure` group. How do we tell what we're configuring?

I haven't thought of an alternative yet. But you mentioned...

> while you want to manage subgroups, but not the group.

I don't think that's what the original issue/desire is. I believe the user is expecting the group to be managed but it's not working. It's only working on subgroup for them. Please correct me in case I'm reading the post wrong.

Out of the 3 variants of config from @escalate , the 1st variant looks correct to me. Not sure why it's not working for them. Need to try and reproduce the issue I think. The 2nd & 3rd variant config seems wrong.

**Comment by gdubicki** [comment]
> (...) How do we tell what we're configuring?

Yes, it could be a project or a group. I initially thought that it's not a problem because we will just apply whatever config is inside to whatever entities are matching (we could throw an error if the config doesn't apply to anything - f.e. when there is a group-level config under such entry while in fact it is a project). But perhaps it's better to distinguish what we expect in the config syntax itself. I just don't have a good idea how could that syntax look like so it's intuitive. Something like `infrastructure/<some symbol>`, perhaps?

> I don't think that's what the original issue/desire is.

I think we are kind of both right.

Firstly there seem to be some _bug_ happening here, because the 1st variant should apply the group members to `infrastructure` group **AND** all its subgroups, f.e. `infrastructure/subgroup1`, `infrastructure/subgroup2` etc.
This surprises me a lot because this variant looks ok to me too and all the tests are using it successfully - see https://github.com/gitlabform/gitlabform/blob/df0e1ae7f1ed6078b8aa72ee07ff3696caf343e6/tests/acceptance/standard/test_group_members_users.py.

But secondly it seems that @escalate does NOT want the group members to be configured in the subgroups but ONLY in the `infrastructure` group - for that we would need to implement a missing _feature_. 

(To make this more complicated, because of unexpected behavior about which [I wrote here](https://github.com/gitlabform/gitlabform/issues/434#issuecomment-1312555696) for now you seem to be able to achieve @escalate's outcome if you run gitlabform ONLY with `gitlabform infrastructure` but NOT with `ALL_DEFINED` or `ALL`. But this behavior will change in the future, although perhaps only in v4 as it's a pretty breaking change.).

**Comment by gdubicki** [comment]
Actually if you have a relatively static list of subgroups within the `infrastructure` group, @escalate, you could use this syntax:

```yaml
config_version: 3

projects_and_groups:
  "infrastructure/*":
    group_members:
      users:
        user1:
          access_level: owner

  # repeat this for each of your subgroup
  "infrastructure/subgroup1/*":
    group_members:
      inherit: false
```

**Comment by amimas** [comment]
> But secondly it seems that @escalate does NOT want the group members to be configured in the subgroups but ONLY in the infrastructure group - for that we would need to implement a missing feature.

Hmm... I guess I mis-interpreted what @escalate  is trying to achieve. But even in that case, I'm not sure gitlabform can do anything about it. Isn't it a built-in feature from Gitlab itself to inherit membership of parent groups?


> able to achieve @escalate's outcome if you run gitlabform ONLY with gitlabform infrastructure but NOT with ALL_DEFINED or ALL.

Ahh... I see. That makes sense now. I am using the first variant config that @escalate posted and it's working for me. I use `ALL_DEFINED` when running gitlabform.

**Comment by escalate** [comment]
> Actually if you have a relatively static list of subgroups within the `infrastructure` group, @escalate, you could use this syntax:

I had also tried this way. However, I don't want to have to remember to adjust config.yml every time a new subgroup is created via the UI. This is not intuitive enough for me and my colleagues.

**Comment by gdubicki** [comment]
> > Actually if you have a relatively static list of subgroups within the `infrastructure` group, @escalate, you could use this syntax:
> 
> I had also tried this way. However, I don't want to have to remember to adjust config.yml every time a new subgroup is created via the UI. This is not intuitive enough for me and my colleagues.

Of course, we also don't want that in the longer term. That would just be a **temporary** workaround. :)

**Comment by gdubicki** [comment]
Thanks for providing more info about what happened, @escalate!

Our code in fact does not use the PUT method and is using a sequence of DELETE and POST instead. And all our our acceptance tests and all kinds of real-world use worked this way with no issues up to this point.

I tried to reproduce your issue [here](https://github.com/gitlabform/gitlabform/pull/469/files#diff-063cc0f88665b51b42ceeee6b3aa85f0257e6682713c96be129996ee8a49fbec) but I was not able to - it "works for me". Can you please share an output of your gitlabform run that throws this HTTP 409 with `--debug` verbosity? You can do it more privately if you join our slack channel, if you prefer that: https://join.slack.com/t/gitlabform/shared_invite/zt-1mojm69tg-IFOlso8JLq3iFwZramCbrw

PS While investigating this I did in fact add support for PUT methods in the above MR, mostly as using PUT should result in cleaner audit logs (not showing misleading removal and adding users), and while I don't expect it help your case, it _might_ help, so I will ping you when this gets merged and released in the next 3.4.0 release candidate/final release so you can retest with it - unless we find the issue sooner based on the logs that I hope you will be able share. :)

**Comment by escalate** [comment]
Thank you for the update.
Also with this version the same error appears.
I have tested further and found that it is due to the case sensitivity of the usernames.
My username has a capital letter at the beginning and at the end.
However, in config.yml I have the usernames all lowercase.
But the check if a user already exists seems to be case sensitive. 
With the correctly written username also the errors disappear.
I thought the upper and lower case does not matter.
The users in our GitLab are from our Active Directory (LDAP).
When logging into Gitlab, the username can be lowercase.
The usernames in config.yml can also be lowercase when adding to a group.
But on the second pass, the users can no longer be found in the group, even though they already exist.

**Comment by gdubicki** [comment]
> Lower case usernames don't work

It seems that we need to make the app case-insensitive for usernames then, like we already do for project and group names.

> I think it would be generally better to split the keyword projects_and_groups into projects and groups.
> Probably it would be easier to distinguish in the code which API has to be addressed.
> Also it would be clearer how to handle the * wildcard and the direct group names.
> In addition, it fits well with the existing two keywords skip_projects and skip_groups.
> This breaking change might be good for config version 4.

Interesting take.

Could you please go ahead a propose a syntax f.e. to provide settings:
* to a group entity and its subgroups/projects,
* to a group entity but NOT its subgroups/projects,
* ONLY to the group's subgroups/projects,
?

**Comment by escalate** [comment]
Hello @gdubicki,

My idea for structuring the YAML file is the following.

To filter the projects I would use the key "path_with_namespace".
See API docs: https://docs.gitlab.com/ee/api/projects.html

To filter the groups I would use the key "full_path".
See API docs: https://docs.gitlab.com/ee/api/groups.html

These are also the keys currently in use.

Example YAML file after split:

```
projects:
    "*":  # All projects
    "group1/project1":  # Only project1
    "group1/*":  # All projects starting with group1/
  
groups:
    "*":  # All groups
    "group1"  # Only group1
    "group2/subgroup1"  # Only subgroup1
    "group2/*"  # All groups starting with group2/ incl. group2
```

All prefixes can be removed from the keys after splitting. e.g. project_ or group_
    
```
projects:
    "*":
        members:
        settings:  # Instead of project_settings
        badges:
        variables: 
  
groups:
    "*":
        members:  # Instead of group_members
        settings:  # Instead of group_settings
        badges:  # Instead of group_badges
        variables:  # Instead of group_variables
        
skip_projects:
    - group1/project1  # Only project1
    - group1/*  # All projects starting with group1/

skip_groups:
    - group1  # Only group1
    - group2/subgroup1  # Only subgroup1
    - group2/*  # All groups starting with group2/ incl. group2
```

Is the explanation helpful for you?

Best regards
Felix
