### ISSUE TITLE
remove_other_approval_rules flag does not actually remove all other approval rules

### ISSUE THREAD

**Issue by M-Murad-Ahmed** [gitlabform/gitlabform#470]
**Describe the bug**

Steps to recreate:
1. Configure your own approval rule in a gitlab project manually (without using gitlab form)
2. Configure project approval settings via gitlab form and set remove_other_approval_rules: true and add new approval rule

Expected:
Pre existing approval rules to be removed

Actual:
Old approval exists and any new rules combined are both added to merge request settings

**GitLabForm version**

3.3.2

**GitLab version**

15.6.3-ee

**Comment by escalate** [comment]
Hello @M-Murad-Ahmed 

I have directly used the GitLabForm version 3.4.0rc3. With this it works without any problems.

Example:
```
config_version: 3

projects_and_groups:
  "infrastructure/*":
    merge_requests_approvals:
      merge_requests_author_approval: false
      reset_approvals_on_push: true
    merge_requests_approval_rules:
      qa:
        name: "Quality Assurance Team"
        approvals_required: 1
        users:
          - user1
          - user2
      enforce: true
```

I hope my answer is helpful for you.

Best regards
Felix
