### ISSUE TITLE
Using old merge requests syntax sometimes results in HTTP 400: "rule_type":["any-approver for the project already exists"]

### ISSUE THREAD

**Issue by gdubicki** [gitlabform/gitlabform#482]
**Describe the bug**

In GitLabForm v3.4.1+ when using the old merge request syntax and when you don't define any `approvers` or `approver_groups`, example:

```yaml
projects_and_groups:
  group/project:
    merge_requests:
      approvals:
        approvals_before_merge: 2
        reset_approvals_on_push: false
        disable_overriding_approvers_per_merge_request: true
```
...this should be interpreted as the new `rule_type: any-approver` kind of a rule, but is not so when you have an existing rule of this kind but _under a different name_ than `Approvers (configured using GitLabForm)` (the default seem to be `All Members`), then GitLabForm tries to create the defined rule as a new one instead of editing the existing one, and this results in an error like:
```
Request url='https://gitlab.company.com/api/v4/projects/4885/approval_rules', method=POST, json='{"approvals_required": 2, "name": "Approvers (configured using GitLabForm)"}' failed - expected code(s) [201], got code 400 & body: '{"message":{"rule_type":["any-approver for the project already exists"]}}'
```

I don't yet know how to properly handle this as trying to add `rule_type: any-approver` in the transformer from the old syntax to the new one is not obvious as in some cases the config may not contain any `approvers` or `approver_groups` because they are inherited, example:

```yaml
projects_and_groups:
  group/*:
    merge_requests:
      approvals:
        approvals_before_merge: 2

  group/project1:
    merge_requests:
      approvals:
        approvers:
          - user1
          - user2

  group/project2:
    merge_requests:
      approvals:
        approvers:
          - user3
          - user4
```

Workaround -> switch to a new syntax.

**GitLabForm version**

v3.4.1+

**GitLab version**

Tested on 15.7.3-ee, but probably it applies to all versions.
