### ISSUE TITLE
Branch protection `allowed_to_push` does not work if it contains individual users

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#485]
**Describe the bug**

GitLabForm config I'm using is listed below. Only included relevant configs.

```yaml
config_version: 3

projects_and_groups:
  # Default settings for ALL projects in "my-group"
  my-group/*:
    project_settings:
      # Default project settings go here
      ...
    merge_requests:
      # Default MR settings go here
      ...
    branches:
      # Default branch protection setting
      main:
        protected: true
        unprotect_access_level: maintainer
        push_access_level: no access
        merge_access_level: developer
        code_owner_approval_required: true

  my-group/project1:
    project_settings:
      description: |
        A brief description about this project
    branches:
      main:
        allowed_to_push:
          - group: users-group1

  my-group/project2:
    project_settings:
      description: |
        A brief description about this project
    branches:
      main:
        allowed_to_push:
          - user: John.Doe
```

With the above config, looks like the `allowed_to_push` setting is being configured for `my-group/project1` properly as expected. But, for `my-group/project2` is not configuring the `allowed_to_push`. The difference between the config is "user" instead of "group".

When I run `gitlabform` in my CI, I use the `--output-file`. Looking at the effective config generated that gitlabform applies, this is how the 2 projects are configured:

```yaml
my-group/project1:
   project_settings:
      description: |
         A brief description about this project
      ...

   merge_requests:
      # Copy of default setting listed here
      ...

   branches:
      main:
         protected: true
         unprotect_access_level: 40
         push_access_level: 0
         merge_access_level: 30
         code_owner_approval_required: true

         allowed_to_push:
         - group_id: '152'

my-group/project2:
   project_settings:
      description: |
         A brief description about this project
      ...

   merge_requests:
      # Copy of default setting listed here
      ...
   branches:
      main:
         protected: true
         unprotect_access_level: 40
         push_access_level: 0
         merge_access_level: 30
         code_owner_approval_required: true
```

Somehow `allowed_to_push` doesn't seem to take any effect if it's configuration is individual user. See effective config for `my-group/project2`. I tried switching to `user_id` instead of `user` but that didn't make any difference.

When the individual users were first configured (about 6 months ago), I was using gitlabform v2.11.1. I checked out the older commit and locally ran dry-run using gitlabform 2.11.1 and I'm seeing same result in the generated effective config. I didn't realize till now that listing individual users didn't work before.

**GitLabForm version**

Output of `gitlabform -V`

```
🏗  GitLabForm version: 3.3.2 = outdated 😔, please update! (the latest stable is 3.4.1)
```

**GitLab version**

F.e. `15.7.5-ee`
