### ISSUE TITLE
Ignore group and project variable changes after creation

### ISSUE THREAD

**Issue by SachinKSingh28** [gitlabform/gitlabform#496]
We use gitlabforms to manage all the configurations but we are not able to manage all of the group and project CI variables yet. We have certain variables which only need to be created initially but need to be ignored when updated. These are variables with access keys and tokens etc which are rotated on a regular interval. 

They need to be present initially so project maintainers know the variables they need to populate.

It would be great if we can add a property `enforce` to variables which defaults to `true` but if set to `false`, it will only create but not update.

**Proposed config**:

```yaml
projects_and_groups:
  group_1/project_1:
    variables:
     variable_created_but_not_updated: 
        key: MY_VAR
        value: "Some variable with access key populated initially and auto rotated regularly."
        enforce: false
```

**Comment by adam-moss** [comment]
This is a challenge with tokens in variables and maintaining consistent config-as-code for sure.  I would be nice to bake a solution in for this.

**Comment by gdubicki** [comment]
Hi @SachinKSingh28 and @adam-moss!

Thank you for the proposal and comment.

We already support such a behavior for `files` with `overwrite: false`, so it would make a lot of sense to add such support to variables as well.

We are very open to PRs that would add it then!

**Comment by amimas** [comment]
I haven't yet come across a use case like this. Would like to understand it more.

> It would be great if we can add a property enforce to variables which defaults to true but if set to false, it will only create but not update.

Doesn't that defeat the purpose of "config-as-code" approach. Similar to "infrastructure-as-code", the config should reflect the current state. Maybe the approach in this case would be something like this:

```yaml
projects_and_groups:
  group_1/project_1:
    variables:
     enforce: false
     variable1: 
        key: MY_VAR
        value: "12345-abcdef"
```

In the above example, variables in `project_1` can be manually created/updated in addition to those in this config and existing variables won't be removed.

> This is a challenge with tokens in variables and maintaining consistent config-as-code for sure.

@adam-moss  - Not sure what you meant by "tokens in variables". Would you mind clarifying?

> We already support such a behavior for files with overwrite: false, so it would make a lot of sense to add such support to variables as well.

I feel `overwrite: false` makes sense for files as they are contents of the git repo. Still unsure if it applies for gitlab settings.
