### ISSUE TITLE
Create schema for config syntax

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#499]
This is a great tool and it'd be good to have some kind of schema for the config syntax. Let's take a look at a simple config example:

```yaml
projects_and_groups:
  group_1/*:
  # Config for all projects under `group_1`
  project_settings:
    # Skipping details to keep the sample short
  branches:
    # Allow merging by developers, but no direct commits
    main:
      protected: true
      push_access_level: no access
      merge_access_level: developer
      unprotect_access_level: maintainer
  group_1/project_1:
    # Special setting for `project_1`
    project_settings:
      topics:
        - foo
        - bar
    branches:
      # Keep this branch unprotected
      develop:
        protected: false
      main:
        # special permission in this project for main branch
        allowed_to_push:
          - user1
          - user2
```

I personally made config mistakes several times. For example:

- `branches` config is further indented making it a property of `project_settings`
- `branches` was mis-spelled as `branchs`

GitLabForm does not report issues in mis-configurations mentioned above. In first case, I believe it gets passed to project settings api as additional parameter which gitlab simply ignores.

Obviously the config is not applied, but mistakes are not easy to see, especially when dealing with large config file containing lots of projects configurations, comments, etc. I spent a lot of time trying to debug reasons for config not being applied. I even opened issues in here only to later find out I made config syntax mistakes.

Ideally it'd be nice to have a linter that can catch mis-configurations in config file. The linter is probably a separate feature request though using tool like "[config-lint](https://github.com/stelligent/config-lint)".

Maybe the first step we can take is to create a [json schema](https://json-schema.org/) for the configuration syntax. Secondly, add the schema to [schemastore](https://www.schemastore.org/json/). Having the schema in this public location makes it available to everyone without taking manual steps because most of the popular IDEs or their extensions/plugins automatically consume it. This gives us auto-complete and syntax issues warnings in our editors.

Extra bonus would've been if gitlab api's schemas were also there. That way gitlabform's schema could refer to gitlab's schema within the objects (i.e. `project_settings`, `branches`, etc.), I think that would've made it whole, but having a config for gitlabform might be the start.

What do you think?
