### ISSUE TITLE
Does gitlabform work on gitlab.com saas?

### ISSUE THREAD

**Issue by yantantether** [gitlabform/gitlabform#502]
I'm trying to use Gitlabform on our organisation's group on gitlab.com. Is this a supported use-case?

As gitlab.com won't let me apply change to the top level, I've skipped the `*` key under `projects_and_groups` and used `my-org/*` and further sub-paths:

```yaml
config_version: 3

gitlab:
  url: https://gitlab.com
  token: "<my token>"

projects_and_groups:
  "my-org/*":
    project_settings:
      default_branch: main
  "my-org/my-group/*":
    members:
      users:
        my-user:
          access_level: maintainer
```

So far I've been unable to assign members to groups. When I add a project underneath, they are added to the project. But I'd like to add at group level.
