### ISSUE TITLE
group_settings are not applied to groups recursively

### ISSUE THREAD

**Issue by SachinKSingh28** [gitlabform/gitlabform#509]
**Describe the bug**

It seems that the group_settings are not applied recursively to group and all its subgroup. The configuration I'm using is as shown below - 

```yaml
config_version: 3
gitlab:
  ssl_verify: true
  timeout: 20
projects_and_groups:
  "*":
    group_settings:
      share_with_group_lock: false
``` 

The command I'm running is -

`gitlabform -c config.yaml <namespace in gitlab.com>`

The command output is - 

```
🏗 GitLabForm version: 3.4.3 = the latest stable 😊
>>> Getting requested groups or projects...
:: # of groups to process: 1
:: # of projects to process: 0
:: (# of omitted projects - archived: xxxx, empty effective config: yyyy)
@ (1/1) Processing group: <namespace in gitlab.com>
:: # of groups processed successfully: 1
:: # of projects processed successfully: 0
```

Other command I have tried is as shown below - 

`gitlabform -c config.yaml ALL_DEFINED`

Output - 
```
🏗 GitLabForm version: 3.4.3 = the latest stable 😊
>>> Getting all groups and projects defined in the configuration...
Error: Configuration does not have any groups or projects defined!
```

I tried running with "ALL" as target too but that seems to be just taking ages and doesn't complete -

`gitlabform -c config.yaml ALL`

```
🏗 GitLabForm version: 3.4.3 = the latest stable 😊
>>> Getting ALL groups and projects...
```

I was expecting that all group and subgroups will have `share_with_group_lock` set to false but have been unsuccessful with all different configurations and CLI options.

**GitLabForm version**

GitLabForm version: 3.4.3 = the latest stable 😊

**GitLab version**

https://gitlab.com

**Comment by amimas** [comment]
I use a self-hosted gitlab instance, so not too sure but looking at the config, I don't think should work.

To me, the below config is to apply group settings to all groups starting from the root group ( because of `*`).

```yaml
projects_and_groups:
  "*":
    group_settings:
      share_with_group_lock: false
```

I don't think you would have access to every top level group's settings in gitlab.com instance. Although, you ran `gitlabform -c config.yaml <namespace in gitlab.com>` command, maybe there's a bug in gitlabform.

Maybe update the config to refer to the group and then use `ALL_DEFINED` when running gitlabform. For example:

```yaml
projects_and_groups:
  "namespace-or-group/*":
    group_settings:
      share_with_group_lock: false
```

**Comment by SachinKSingh28** [comment]
@amimas I have tried that too! It only applies the setting to **namespace-or-group** and if we update the config to - 

```
projects_and_groups:
  "namespace-or-group/some-sub-group/*":
    group_settings:
      share_with_group_lock: false
```

then the config is only applied to **namespace-or-group/some-sub-group** only but not recursively.
