### ISSUE TITLE
Variable substitution in the `config.yml`

### ISSUE THREAD

**Issue by RajasGujarathi** [gitlabform/gitlabform#524]
_We are using GitLab CI_

We are unable to have variables in `config.yml` as they are not getting substitutied during the run time, and then we end up having actual values in `config.yml`. 

We do not have an encrypted token, which means directly putting it in `config.yml` is a risk. Although, we have the token as an environment variable and therefore we wish to make use of variables inside `config.yml`

.gitlab-ci.yml

```yaml
image:
  name: 'ghcr.io/gitlabform/gitlabform:latest'
  pull_policy: if-not-present

stages:
  - "Execute"

apply-automated-gitlab-configuration:
  stage: 'Execute'
  tags:
    - default
  script:
    - gitlabform ALL
```

config.yml
```yaml
# This key is required in configs for GitLabForm version
config_version: 3

# GitLab API access config
gitlab:
  url: ${CI_SERVER_URL}
  token: ${CI_JOB_TOKEN}
  ssl_verify: true
  timeout: 10

# Configuration to apply to GitLab projects, groups and subgroups
projects_and_groups:
  ....
  ....
  ....
  ....
```

What are we doing wrong?

**Comment by RajasGujarathi** [comment]
Ok, yes sure. Thanks for the input.
Will give it a try.

**Comment by RajasGujarathi** [comment]
config.yml

```yaml
# This key is required in configs for GitLabForm version
config_version: 3

# GitLab API access config
gitlab:
  url: "{{GITLAB_URL}}"
  token: "{{GITLAB_TOKEN}}"
  ssl_verify: true
  timeout: 10

# Configuration to apply to GitLab projects, groups and subgroups
projects_and_groups:
  ....
  ....
  ....
  ....
```

Doing this also does not help, and I get 
`Request url='<GITLAB_URL>/api/v4/version?per_page=100, method=GET, failed - expected code(s) [200], got code 401 & body: '{"message":"401 Unauthorized"}'`

However, if I hardcode the same values then it works 🤔

Is this `"{{GITLAB_TOKEN}}"` the correct way to reference it?

**Comment by RajasGujarathi** [comment]
Using the following `config.yml` fixed it

```yaml
# This key is required in configs for GitLabForm version
config_version: 3

# Configuration to apply to GitLab projects, groups and subgroups
projects_and_groups:
  ....
  ....
  ....
  ....
```

**Changes**:

- Setting `GITLAB_URL` & `GITLAB_TOKEN` as environment variables 
- Removing the `gitlab` top-level key from `config.yml`
