### ISSUE TITLE
Variable deletion is unsuccessful due to environment scope

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#533]
**Describe the bug**

I have a config for a project whose CI CD variables are configured using the same key but scoped to different "environment" with different values. The config looks something like this:

```yaml
my-group/*:
    variables:
      # Remove unconfigured variables from **all projects**.
      enforce: true

my-group/sub-group/project1:
   variables:
      aws_access_key_id_review:
         key: AWS_ACCESS_KEY_ID
         value: ******
         protected: false
         masked: false
         environment_scope: review/*
         filter[environment_scope]: review/*
      aws_access_key_id_review:
         key: AWS_ACCESS_KEY_ID
         value: ******
         protected: false
         masked: false
         environment_scope: staging/*
         filter[environment_scope]: staging/*
```

In the above config, I have set `enforce: true` for all projects. This ensures any unconfigured projects in that group will have it's variables deleted. It works, but I just came across an edge case.

I removed the `my-group/sub-group/project1` config. After running `gitlabform` I get following error message:

```
Warning: Error occurred while processing project my-group/sub-group/project1, exception:
Request url='https://gitlab.example.com/api/v4/projects/my-group/sub-group/project1/variables/AWS_ACCESS_KEY_ID', method=DELETE, failed - expected code(s) [204, 404], got code 409 & body: '{"message":"There are multiple variables with provided parameters. Please use 'filter[environment_scope]'"}'
```

I suspect `gitlabform` does not does not have the context or set `filter[environment_scope]` parameter when calling the api for variable deletion. Also not sure if this is due to the project being in sub-group. I did come across edge case related to sub-group and variable enforcement before. See #457 for details.

**GitLabForm version**

Output of `gitlabform -V`:  `🏗 GitLabForm version: 3.4.3 = outdated 😔 , please update! (the latest stable is 3.5.0)`

**GitLab version**

`15.9.3-ee`
