### ISSUE TITLE
[Bug] - Duplicate Pipeline schedules

### ISSUE THREAD

**Issue by RajasGujarathi** [gitlabform/gitlabform#535]
**Describe the bug**

We have a GitLab project, and the pipeline of this project needs to run once a day in order to achieve a defined task. In order to achieve daily runs we are using Scheduled pipelines (_Gitlabform Pipeline schedules_).

With the following configuration, every time the pipeline runs, it creates a new schedule every 2nd time

```
some-project:

    # Periodic execution Schedule
    schedules:
        "Daily":
            description: "Execute Pipeline daily, to avoid configuration divergence"
             ref: main
             cron: 0 3 * * * # Daily at 3:00 AM
             active: true
```

Observation,

> First Run: Schedule created with Description _Daily_
> Second Run: Schedule updated with Description _Execute Pipeline daily, to avoid configuration divergence_
> Total Schedules: 1

> Third Run: Schedule created with Description _Daily_
> Fourth Run: Schedule updated with Description _Execute Pipeline daily, to avoid configuration divergence_
> Total Schedules: 2

**Working Fix**

Schedules works as expected after changing the configuration to _(`description` attribute has been removed)_ :

```
some-project:

    # Periodic execution Schedule
    schedules:
        "Daily":
             ref: main
             cron: 0 3 * * * # Daily at 3:00 AM
             active: true
```

**GitLabForm version** 
🏗 GitLabForm version: 3.5.0 = the latest stable 😊

**GitLab version**
GitLab Enterprise Edition 15.8.0-ee
 
**Credits**:
Working fix provided by (_Removing `description` attribute_) - Aver Mimas (@amimas)
