### ISSUE TITLE
Add `enforce` support to schedule pipeline config

### ISSUE THREAD

**Issue by amimas** [gitlabform/gitlabform#539]
Currently the scheduled pipeline configuration syntax is like this:

```yaml
   group-name/project-name:
    schedules:
      Title of the schedule:
        ref: <branch-name>
        cron: <cron-expression>
        cron_timezone: <time-zone>
        variables:
          PIPELINE_VARIABLE1:
            value: <variable-value>
```

Consider the following 2 cases:

- Rename the "Title of the schedule" to something else
- Delete the entire schedule

In the first case, a new schedule will be created; existing schedule will remain in the project. For the 2nd case, nothing happens. The schedule from previous run of `gitlabform` will remain in the project.

In most cases the above is probably not expected. It'd be good to have `enforce: true` support for the `schedules` config so that any "unconfigured schedules" are deleted.
