### ISSUE TITLE
How do you create an environment?

### ISSUE THREAD

**Issue by kaihendry** [gitlabform/gitlabform#540]
I have a config like:

```
protected_environments: # to approve deployments
      prd:
        deploy_access_levels:
          - access_level: maintainer # only devops can approve production deployments
        required_approval_count: 1
      stg:
        deploy_access_levels:
          - access_level: developer
        required_approval_count: 1

```

It has correctly formed the policy:

![image](https://user-images.githubusercontent.com/765871/236118931-dc1965ba-f6ef-4f51-9d3f-0b8a5a483c70.png)

But it hasn't created the "prd" environment:

![image](https://user-images.githubusercontent.com/765871/236118711-4b4c345e-b9c9-4c63-858e-ccbdae3684e9.png)

What am I missing please?
