### ISSUE TITLE
Breaking Inheritance not working in branches section

### ISSUE THREAD

**Issue by RajasGujarathi** [gitlabform/gitlabform#543]
**Describe the bug**

Facing an issue with the effective configuration for the `branches` section.

`config.yaml`

```projects_and_groups:
  group_1/*:
    branches:
      main:
        protected: true
        push_access_level: no access
        .
        .
        .

  group_1/project_1:
    branches:
      prod:
        protected: true
        push_access_level: no access
        .
        .
        .
```

I do not want the `main` branch, set at `group_1`, to appear in the `project_1`. So when I tried using `inherit: false` it failed to generate the effective configuration.

`config.yaml`

```projects_and_groups:
  group_1/*:
    branches:
      main:
        protected: true
        push_access_level: no access
        .
        .
        .


  group_1/project_1:
    branches:
      inherit: false
      prod:
        protected: true
        push_access_level: no access
        .
        .
        .
```

![image](https://github.com/gitlabform/gitlabform/assets/31616516/7099219f-d132-4856-be52-9b49deda856a)

**GitLabForm version**
🏗 GitLabForm version: 3.5.0 = the latest stable 😊

**GitLab version**
GitLab Enterprise Edition 15.8.0-ee

**Comment by amimas** [comment]
I did a quick test but couldn't reproduce the issue. Here's how I tested it:

- Running latest version of gitlabform (`3.7.0`)
- Running  in docker latest version of gitlab locally (`v16.1.2-ee`)
- Created a group named `group-issue-543`
- Created 2 projects under the above group named `project1` and `project2`
- Created the following config in a directory:

```yaml
config_version: 3

projects_and_groups:
  group-issue-543/*:
    branches:
      main:
        protected: true
        push_access_level: no access
        merge_access_level: developer
        unprotect_access_level: maintainer
```

- Ran `gitlabform --config ./reproduce-issue/config.yml ALL_DEFINED`: This configured the `main` branch protection as expected according to the above config in both `project1` and `project2`
- Updated the config to break inheritance for `project2`

```yaml
config_version: 3

projects_and_groups:
  group-issue-543/*:
    branches:
      main:
        protected: true
        push_access_level: no access
        merge_access_level: developer
        unprotect_access_level: maintainer


  group-issue-543/project2:
    branches:
      inherit: false
      prod:
        protected: true
        push_access_level: no access
        merge_access_level: developer
        unprotect_access_level: maintainer
```

- Ran `gitlabform --config ./reproduce-issue/config.yml ALL_DEFINED`: This time gitlabform ran successfully for me. The `project2` now has an additional branch protection named `prod`. I had to manually delete the `main` branch protection since we didn't have the `enforce: true` config set. I re-ran the above command and it still ran successfully.

```
(venv) ➜  gitlabform git:(issue-543) ✗ gitlabform --config ./reproduce-issue/config.yml ALL_DEFINED
🏗 GitLabForm version: 3.7.0 = the latest stable 😊
>>> Getting ALL groups and projects DEFINED in the configuration...
:: # of groups to process: 0
:: (# of omitted groups - empty effective config: 1)
:: # of projects to process: 2
* (1/2) Processing project: group-issue-543/project1
* (2/2) Processing project: group-issue-543/project2
:: # of groups processed successfully: 0
:: # of projects processed successfully: 2
:: All requested groups/projects processed successfully! ✨
```

@RajasGujarathi - Did I miss any step or mis-configure anything?
