### ISSUE TITLE
Issue with Merge Request Rules for specific branches

### ISSUE THREAD

**Issue by LucianoAdonis** [gitlabform/gitlabform#547]
Hello!

I'm trying to define approvers for MRs based on the branch, the groups are created correctly, but I get in all scenarios as Target branch "All branches."

I can manually define the branches from the GUI, but then Gitlabform overwrites the config. Am I missing something?

I tried this with versions 3.4.3 and 3.5.0 and got the same result. Below is a simplified version of what I'm running. 

```
myproject:
    branches:
      main:
        protected: true
        push_access_level: maintainer
        merge_access_level: 30 # Developers + Maintainers
        unprotect_access_level: maintainer
        allow_force_push: false
      develop:
        protected: true
        push_access_level: maintainer
        merge_access_level: 30 # Developers + Maintainers
        unprotect_access_level: maintainer
        allow_force_push: false
    merge_requests_approvals:
      disable_overriding_approvers_per_merge_request: true
    merge_requests_approval_rules:
      esd-team:
        approvals_required: 1
        name: "First Team"
        users:
          - MyUserName
        branches:
          - develop
      any: # this is just a label
        approvals_required: 1
        name: "Any member"
        rule_type: any_approver
      enforce: true
```

Without the enforcement, I'll still get the Target branch reverted to "All branches." So I feel it's something on my end, but I can't put my finger on it.

Any help is appreciated, thank u!
