### ISSUE TITLE
How to set merge_method option for a project

### ISSUE THREAD

**Issue by Panicali** [gitlabform/gitlabform#577]
The feature I would like to propose is the ability to specify the "merge_method" for projects. The implementation should be achievable using this API: https://docs.gitlab.com/ee/api/projects.html#edit-project by setting the "merge_method" attribute.

**Comment by amimas** [comment]
Hello @Panicali . This is already supported because `merge_method` is part of Project settings. The config would look like this:

```yaml
projects_and_groups:
  group_1/project_1:
    project_settings:
      default_branch: main
      merge_method: rebase_merge
      .... # other project settings supported by the Edit Project API
```
