### ISSUE TITLE
Skipping Nested Projects/groups ?

### ISSUE THREAD

**Issue by josue-sanchez-wabtec** [gitlabform/gitlabform#579]
Hello, 

Is there any way to skip nested projects, I have this situation:

projects_and_groups:
   general/subgroup/specific_group/*:
     <some config>
   general/*:
     <some config>

Image reference:
![image](https://github.com/gitlabform/gitlabform/assets/114017629/df96e931-431c-4d37-b624-b57ba2eabd52)

The general config is applied for all the projects in which subgroup/specific_group is part of the general group.

But I see the configuration could be overwritten by "gitlabform -v general" as for "gitlabform -v general/subgroup/specific_group" I have another branches configuration.

So is there any way to add the skip_projects flag inside each config section ? Something like:

projects_and_groups:
   general/subgroup/specific_group/*:
     <some config>
   general/*:
     <some config>
     skip_projects:
       - general/subgroup/specific_group/*
       
Image Reference:
![image](https://github.com/gitlabform/gitlabform/assets/114017629/10c382d2-fc56-4526-abfb-3883d1b79528)

       
Thank you so much for your advice.

**Comment by josue-sanchez-wabtec** [comment]
@amimas  thank you so much for your response.

As you can see there are some overlapped projects  on my test, these projects are "general/subgroup/specific_group/*" all of the projects inside this specific_group subgroup.

What I am trying to achieve is to set some particular configuration only for this projects that are inside this  "specific_group" subgroup, but I noticed the "general/*" group configuration section is changing these configuration for the special subgroup I mentioned as this clause is a more inclusive one, so "general/*" has inside all my desired projects at "general/subgroup/specific_group/*". I was wondering if there is any way to exclude on the "general/*" configuration section my special projects "general/subgroup/specific_group/*" so the configuration will only follows what I declare under :

general/subgroup/specific_group/*:
   Some configuration ...
   
An not  under

general/*:
  Some configuration ...

**Comment by amimas** [comment]
Sorry, I'm not sure I understood your explanations clearly. Here's what I'm guessing you're looking for. Hopefully the config sample and the comments below makes sense.

```yaml
projects_and_groups:
  general/*:
    # Default settings for all projects under 'general' group goes here:
    project_settings:
      <some-project-settings>
    branches:
      main:
        protected: true

  general/subgroup/*:
    # Default settings for all projects under 'general/subgroup' group goes here:
    project_settings:
      <some-project-settings>
    branches:
      subgroup-dev:
        protected: true

  general/subgroup/specific_group/*:
    # Default settings for all projects under 'general/subgroup/specific_group' group goes here:
    project_settings:
      <some-project-settings>
    branches:
      specific-group-dev:
        protected: true

  general/subgroup/specific_group/special_project1:
    # Special setup only for 'special_project1` project
    project_settings:
      topics:
        - foo
        - bar
    branches:
      special-branch:
        protected: true
        allowed_to_push: no access
        allowed_to_merge: developer
```

**Comment by josue-sanchez-wabtec** [comment]
@amimas 

lets say we have this instead

projects_and_groups:
  general/*:
    # Default settings for all projects under 'general' group goes here:
    project_settings:
      <some-project-settings>
    branches:
      main:
        protected: true

  general/subgroup/*:
    # Default settings for all projects under 'general/subgroup' group goes here:
    project_settings:
      <some-project-settings>
    branches:
      subgroup-dev:
        protected: true

  general/subgroup/specific_group/*:
    # Default settings for all projects under 'general/subgroup/specific_group' group goes here:
    project_settings:
      <some-project-settings>
    branches:
      specific-group-dev:
        protected: true

  general/subgroup/specific_group/special_project1:
    # Special setup only for 'special_project1` project
    project_settings:
      topics:
        - foo
        - bar
    branches:
      special-branch:
        protected: true
        allowed_to_push: no access
        allowed_to_merge: developer

**Comment by josue-sanchez-wabtec** [comment]
Well lets say actually I have this:


projects_and_groups:
  general/*:
    # Default settings for all projects under 'general' group goes here:
    project_settings:
      <some-project-settings>
    branches:
      main:
        protected: true
     release:
        protected: true

  general/subgroup/*: 
    # Default settings for all projects under 'general/subgroup' group goes here:
    project_settings:
      <some-project-settings-for-subgroup>
    branches:
      main:
        protected: true

  general/subgroup/specific_group/*:
    # Default settings for all projects under 'general/subgroup/specific_group' group goes here:
    project_settings:
      <some-project-settings-for-specific_group>
    branches:
      main:
        protected: true
        
#skip_projects:
#   - general/subgroup/specific_group/*

I do not need release branch on the projects under general/subgroup/, lets say I have 75. If I run general/* configuration this  will modify them and the release branch configuration will be added. I am automating the process so I am executing the following:

gitlabform -v general
gitlabform -v general/subgroup

I have the skip_projects attribute but this does not let me apply the second statement so I have it commented . So I was wondering if base on my context, is there any solution to exclude a subgroup from a higher/parent group gitlabform sentence that is changing some configuration in the subgroup but that I want other other consideration like this branch declarations? 

If I apply this flow all projects on general/* including the ones inside general/subgroup will have the release branches declared as protected, something I am not looking for.

My general group structure is:

general/ :

100 projects and 50 groups


one of these groups is general/subgroup/specific_group/ (Which has 75 projects)

So applying gitlabform -v general will add all the projects configuration for 100 projects and 49 groups (and the projects inside ).

I think a posible solution could be think backwards, I can declare of course the general sentence with only 
 ```
  general/*:
    # Default settings for all projects under 'general' group goes here:
    project_settings:
      <some-project-settings>
    branches:
      main:
        protected: true
```
And add the

```
     release:
        protected: true
```
section in other groups projects sentences as

```
  general/subgroup-1/*:
  ...
  general/subgroup-2/*:
  ...
  general/subgroup-3/project-specific:
  ...
  
```

So this way the flow will be additive not a subtraction flow as I think I have it, but then this approach will force me to have a big long config.yaml file declaring all the projects needed.
