### ISSUE TITLE
Direct membership to all projects under a group to get CODEOWNERS MR approval to work

### ISSUE THREAD

**Issue by xmath279** [gitlabform/gitlabform#581]
We were hoping to use GitLabForm to configure code owner groups to more easily manage who can approve what.

However, as per GitLab's documentation (https://docs.gitlab.com/ee/user/project/codeowners/#inviting-subgroups-to-parent-groups), in order for the approval to be required, the group must be added as a direct member to the project.

In GitLabForm, I have configured my additional group that is to be used for code owner rules in MR approvals like so:

```yaml
"org/*":
  group_members:
   groups:
     codeowners/devops:
       group_access: developer
```

Unfortunately, GitLabForm's default behaviour for this configuration is incompatible with GitLab's restriction where groups to be used as code owners must be direct members to the projects. Currently, the group is instead added to the "org" group to be inherited by all child projects. This works fine for giving access to people, but not for using them as codeowner groups.

If there a was a way to configure GitLabForm so that is applies the membership to each child projects invidually, this would solve this issue.

I'm sorry if this is already possible, I could not find the way to configure that from the documentation.

**Comment by amimas** [comment]
The config sample you've got actually processes all the groups and subgroups under `org/*` namespace and adds `codeowners/devops` group as a member to those groups, because of `group_members` config.

Since you're looking to add `codeowners/devops` as a member to the projects under `org/*` namespace, I believe what you want is this:

```yaml
"org/*":
  members:
   groups:
     codeowners/devops:
       group_access: developer
```

Docs: https://gitlabform.github.io/gitlabform/reference/members/#project-members
