### ISSUE TITLE
Can it do these things:

### ISSUE THREAD

**Issue by andrei-abusan** [gitlabform/gitlabform#6]
Looks really cool, had a quick try with it and there's a few things I'm not able to get working, wondering if they can be done and if yes how:

- set group visibility
- apply configuration to projects in subgroups recursively
- create group
- create project
- use project name (and potentially other information gathered) as a parameter in config strings (usecase here is I need to create a hook that has project name in the url  for every project)

**Comment by gdubicki** [comment]
Hey @andrei-abusan, unfortunately none of these things is possible as of now.

I believe that setting group visibility would be trivial to add and I can do that.

I don't think that we use subgroups so I would prefer to get a PR for this.

As for creating groups and projects: do you have a proposal for how it could be designed? I mean the config syntax and the flow, I would think of the implementation.

Using project name is something I have already been considering along with support for templates in files section, so this may be added pretty soon by us.

**Comment by andrei-abusan** [comment]
Hi @gdubicki thanks for the quick reply. 

WRT creating groups and projects, I think it could actually work with existing syntax. If you specify a set of configuration for a group and said group doesn't exist, create it. If it does exist just update the settings for it. You would end up with blank configuration for all the projects you are creating but that can double as a readymade "overrides" section for said project if ever you want to add any. Possibly have a boolean to say whether to create if not present? So I would expect below to create the group and the project inside it with whatever settings gitlab is set to default to globally. 

```
gitlab:
  url: http://company.gitlab.com
  token: "<token_here>"

group_settings:
   'my_group': # common settings for ALL projects in this project group
project_settings:
  'my_group/my_project':
    'createIfNotPresent': true # flag to toggle feature if you think it's worth having
    project_settings:
```
Great to hear that you were already considering templating and gathering information, I think that would significantly expand what can be done with the tool!

I'm still not sure if we will be using a hosted GitLab instance yet as we are still weighing pros and cons but if we do, this could be really useful in automating at least parts of our migration as well as leaving us in a better place with configuration as code and an automated system for creating projects. Cheers to you for making this and open-sourcing it!
