### ISSUE TITLE
when running for a single group, its subgroups should be included

### ISSUE THREAD

**Issue by exaV** [gitlabform/gitlabform#613]
There is currently a unintuitive behaviour when it comes to running config for a single group.

Consider the following config file:

```yaml
csi/*:
        project_settings:
            allow_merge_on_skipped_pipeline: false

csi/my-subgroup/*
      group_members:
          users:
              myself:
                  access_level: maintainer

csi/my-subgroup/project-a:
            allow_merge_on_skipped_pipeline: true
csi/project-b:
            allow_merge_on_skipped_pipeline: true
```

Here we define some settings for projects inside the top level `csi` group. We also specifically add some users as group members to the group `csi/my-subgroup`. Unfortunately settings for that subgroup are only applied when we run with `ALL_DEFINED` or `ALL` or `csi/my-subgroup` but not when we run for `csi`. Considering the behaviour of `ALL` I find this a bit counter-intuitive.

Example output:
`pipx run gitlabform csi`:

🏗 GitLabForm version: 3.8.0 = the latest stable 😊
>>> Getting requested groups or projects...
:: # of groups to process: 1 <---------------------------------------- subgroup is excluded
:: # of projects to process: 2

`pipx run gitlabform ALL_DEFINED`:
>>> Getting requested groups or projects...
:: # of groups to process: 2 <---------------------------------------- subgroup is included
:: # of projects to process: 2

**What should happen:**
Running `pipx run gitlabform csi` should also update all subgroups of csi.
