### ISSUE TITLE
Change to protected_environment deploy_access_levels is not detected

### ISSUE THREAD

**Issue by hertzsprung** [gitlabform/gitlabform#644]
**Describe the bug**

Changing gitlabform protected_environment deploy_access_levels from `user` to `access_level` does nothing (debug logs erroneously state: "myenv of protected_environments in mygroup/myproject doesn't need an update"

Config before:
```
mygroup/myproject:
  protected_environments:
    enforce: true
    myenv:
      deploy_access_levels:
        - user: my-user
```

Config after:
```
mygroup/myproject:
  protected_environments:
    enforce: true
    myenv:
      deploy_access_levels:
        - access_level: developer
```

**GitLabForm version**

3.8.0

**GitLab version**

GitLab Enterprise Edition 16.7.0-pre [65594f41831](https://gitlab.com/gitlab-org/gitlab/-/commits/65594f41831)
