### ISSUE TITLE
Error while processing group sharing

### ISSUE THREAD

**Issue by wrbbz** [gitlabform/gitlabform#645]
Hello!

I've got a strange error and do not know why is it occur. So, the situation is:
I've got several groups. One as ACL, another one with some code base. I would like to share the second one with the first one.
So, the first one, lets say - `acl/team`, another one - `product/codebase`. And my config looks like that:
```
  "acl/team/*":
    visibility: private
    enforce: true
    group_members:
      users:
       . . . 
  "product/codebase/*":
    enforce: true
    visibility: private
    group_members:
      groups:
        acl/team:
          group_access: 40
```

On the first run everything is ok. There is no errors or warnings:

```sh
:: # of projects processed successfully: 1
:: All requested groups/projects processed successfully! ✨
```

However, second and following runs give me an error:
```
Warning: Error occurred while processing group product/codebase, exception:

Request url='https://somegitlabdomain.com/api/v4/groups/product%2Fcodebase/share', method=POST, data='{"expires_at": null, "group_access": 40, "group_id": someID}' failed - expected code(s) [200, 201], got code 409 & body: '{"message":"Shared group The group has already been shared with this group"}'
```
And I do not understand what is going on.
If I add another group to `group_members` of `product/codebase`, there would not be any problems with that group. Only with `acl/team`. 

Used GitLabForm version is 3.8.0:
```sh
GitLabForm version: 3.8.0 = the latest stable
```

**Comment by amimas** [comment]
What's the full `gitlabform` command you're using?

**Comment by wrbbz** [comment]
I've used several ways:

```sh
$ gitlabform ALL_DEFINED
```

and

```sh
$ gitlabform product/codebase
```

**Comment by wrbbz** [comment]
> The config has some errors
I've fixed them. Nevertheless, outcome is the same

> Could you post the full config in this scenario?
This is somewhat full config:

```
config_version: 3

gitlab:
  url: https://somegitlabdomain.com
  api_version: 4

projects_and_groups:
  "acl/*":
    project_settings:
      visibility: private
    group_members:
      enforce: true
      users:
        a.zorin:
          access_level: 50

  "acl/team/*":
    project_settings:
      visibility: private
    group_members:
      enforce: true
      users:
        f.name:
          access_level: 50
        s.name:
          access_level: 40

  "team/*":
    project_settings:
      visibility: private
    group_members:
      enforce: true
      users:
        f.name:
          access_level: 50
        s.name:
          access_level: 40

  "product/codebase/*":
    project_settings:
      visibility: private
    group_members:
      enforce: true
      groups:
        acl/team:
          group_access: 40
```
