### ISSUE TITLE
3.9.0 appears to break while setting a project webhook with a token

### ISSUE THREAD

**Issue by clrxbl** [gitlabform/gitlabform#685]
**Describe the bug**

The following message gets thrown when token is set in a project webhook:
```
* (216/311) Processing project: <project>
Warning: Error occurred while processing project <project>, exception:
'token'
```

This only started happening on 3.9.0, reverting to 3.8.0 fixes this issue.

**GitLabForm version**

ghcr.io/gitlabform/gitlabform:3.8.0

**GitLab version**

v16.9.0-ee

**Comment by amimas** [comment]
Thanks for reporting. Could you share the config example? Is this happening for a new project config or just processing existing project? Also are you able to run gitlabform with debug enabled? Debug logs might be help.

**Comment by clrxbl** [comment]
> Thanks for reporting. Could you share the config example? Is this happening for a new project config or just processing existing project? Also are you able to run gitlabform with debug enabled? Debug logs might be help.

Processing existing projects.

I can only provide an example config of how I've configured it:
```yaml
  hooks:
    "http://example.com":
      push_events: false
      job_events: true
      pipeline_events: true
      token: ${TOKEN}
```
