### ISSUE TITLE
Being able to set merge request approvals on group level

### ISSUE THREAD

**Issue by rogierlommers** [gitlabform/gitlabform#701]
Hey! First of all, I like your project. We're playing a bit with our gitlab configurations and how to apply it within the organization. The documentation is quite clear for us, but there is one thing I don't really understand.

<img width="517" alt="Screenshot 2024-03-06 at 14 50 11" src="https://github.com/gitlabform/gitlabform/assets/3907131/b6540580-8647-47d2-a871-92f03d0a205e">

We want to set the request-approval-rules on a group basis. This setting should be inherited to all the groups/projects that will be created inside this group. is this possible?

With the code snippet below i can "walk through" all repositories and change the settings after creation. However, I want to avoid that new projects/repos have the setting `prevent approval by author` to value `false`.

```
---
config_version: 3
gitlab:

projects_and_groups:
  '*':
    merge_requests_approvals:
      reset_approvals_on_push: false
      merge_requests_author_approval: true
      disable_overriding_approvers_per_merge_request: true
```
