### ISSUE TITLE
Feature Flags support

### ISSUE THREAD

**Issue by glensc** [gitlabform/gitlabform#707]
GitLab has feature flags:
- https://docs.gitlab.com/ee/operations/feature_flags.html

API description:
- https://docs.gitlab.com/ee/api/feature_flags.html

I can't seem be able to find feature flags from the feature list:
- https://gitlabform.github.io/gitlabform/features/

nor from issues or pull requests:
- https://github.com/gitlabform/gitlabform/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+feature+flags
- https://github.com/gitlabform/gitlabform/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+feature+flags

please add support controlling feature flags:
- add feature flag
- remove feature flag
- add feature flag only if missing

**Comment by amimas** [comment]
Thanks for the idea @glensc . I think it should probably be another top-level key under a project similar to `branches`, `deploy_keys`, `hooks`, etc. Can you suggest a full config syntax for this feature? Some of the other configs supports `enforce` key so that if something only exists in gitlab but not in gitlabform config, they'll be removed. Should that be included too? BTW - would you be able to help implement it?

**Comment by glensc** [comment]
```yml
projects_and_groups:
  group_1/project_1:
    feature_flags:
      awesome_feature:
        name: awesome_feature
        description: "This feature is about merge train"
        active: true,
        scopes: []
        strategies: ...
        strategies:name: ...
```

- https://docs.gitlab.com/ee/api/feature_flags.html#create-a-feature-flag


from the options only "name" is required, the others ("id", "version") are internal and should be provided by gitlabform.

<img width="527" alt="image" src="https://github.com/gitlabform/gitlabform/assets/199095/7448bc02-bc58-4f82-b2ea-a6fcc525a3d2">

I personally, don't know much about strategies, I just fill from the UI:
- name
- description
- active
- environment (scopes)

so that could be the minimum scope implemented.

also, it's important to have configuration not to overwrite the value of "active". the reason is that the current active flag is changed by product manager (or the like), not tied to configuration of the feature flag.

don't know whether or how other configuration keys handle this. could be similar to them.

and if there is nothing similar for other keys, could implement like that:
- if "active" key is not present, do not update it
- for new flags hardcode "true" or "false" value. not whatever seems logical or convenient. in gitlab UI default is "true"

<img width="634" alt="image" src="https://github.com/gitlabform/gitlabform/assets/199095/41b55f52-4c25-4ef7-837d-365e3709c689">

**Comment by amimas** [comment]
Thanks for all that details @glensc . I haven't used GitLab's "Feature flags" yet, but here's my thought.

I like your config syntax suggestion. One minor tweak I would propose is to not have the `name` key in the config. So, it'll look something like this:

```diff
projects_and_groups:
  group_1/project_1:
    feature_flags:
      awesome_feature:
-       name: awesome_feature
        description: "This feature is about merge train"
        active: true,
-        scopes: []
```

The reason for removing `name` is because it becomes duplicate config. I think gitlabform should use the key named `awesome_feature` and use that for the `name` value. This is consistent with the [pipeline schedule](https://gitlabform.github.io/gitlabform/reference/pipeline_schedules/) config pattern, where the config key is used as the schedule's description. Also, I don't see `scope` in GitLab's API. Maybe you meant that to `strategies:scopes` because I see that one exists.

> also, it's important to have configuration not to overwrite the value of "active". the reason is that the current active flag is changed by product manager (or the like), not tied to configuration of the feature flag.

I'm not too clear or maybe on the fence on this. I think gitlabform should perform based on whatever is in the config. If `active` is not present, default should follow whatever Gitlab does. If `active` key is present in the config, then forward the value to gitlab's api. It's possible I completely misunderstood your explanation :)

As for the config syntax related to `strategies`, maybe we can just write it in a more human friendly way:

```yaml
projects_and_groups:
  group_1/project_1:
    feature_flags:
      awesome_feature:
        description: "This feature is about merge train"
        active: true,
        strategies:
          - strategy-foo: # This is just a label
            name: gradualRolloutUserId
            parameters:
              groupId: default
              percentage: 25
            scopes:
              - environment_scope: staging
          - strategy-bar: # This is just a label
            name: gradualRolloutUserId
            parameters:
              groupId: default
              percentage: 35
            scopes:
              - environment_scope: qa
```

Maybe the `strategies` should be implemented separately. It might be easier to implement the feature flags configs first. Within `strategies` config there are multiple delete type actions; e.g: `strategies:_destroy`, `strategies:scopes:_destroy`.
