### ISSUE TITLE
merge_requests_approval_rules does not respect protected_branches and breaks execution

### ISSUE THREAD

**Issue by hiaik** [gitlabform/gitlabform#720]
**Describe the bug**

`merge_requests_approval_rules` does not work with `protected_branches` inside:
```
projects_and_groups:
  "test-project":
    merge_requests_approval_rules:
      no-approvals-for-staging:
        name: no-approvals-for-staging
        protected_branches:
          - production
          - staging
        approvals_required: 0
```

It breaks the execution:
`docker run -it -v $PWD:/app -w /app ghcr.io/gitlabform/gitlabform:3.9.2 sh -c 'gitlabform -c test-config.yml "test-project"'`

results in:
```
🏗 GitLabForm version: 3.9.2 = the latest stable 😊
Warning: Connected as non-admin. You may encounter permission issues.
>>> Getting requested groups or projects...
:: # of groups to process: 0
:: # of projects to process: 1
* (1/1) Processing project: test-project
Warning: Error occurred while processing project test-project, exception:

Resource with url='https://CLEANDED/api/v4/projects/test-project/protected_branches/production?per_page=100' not found (HTTP 404)!
:: # of groups processed successfully: 0
:: # of projects processed successfully: 0
:: # of projects failed: 1 
:: Failed project 1: test-project
```

You can see that first element from `protected_branches` which is `production` is passed to URL (...protected_branches/production?per_page=100) and breaks it (404).

The same as we have:
```
projects_and_groups:
  "test-project":
    merge_requests_approval_rules:
      no-approvals-for-staging:
        name: no-approvals-for-staging
        protected_branches: test
        approvals_required: 0
```

so `protected_branches: test`. URL will be `...protected_branches/t?per_page=100` so `t` as first letter in `test` will be concatenated to URL and breaks it.

**GitLabForm version**
3.9.2 (latest at the time of creation this bug)

**GitLab version**
[v16.10.0-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.10.0-ee)

**Comment by hiaik** [comment]
documentation says it should work

https://gitlabform.github.io/gitlabform/reference/merge_requests/#rules
`protected_branches - an array of branch names.`

with Examples: https://gitlabform.github.io/gitlabform/reference/merge_requests/#examples

Example 4
```
projects_and_groups:
  group_1/project_1:
    merge_requests_approvals:
      disable_overriding_approvers_per_merge_request: true
    merge_requests_approval_rules:
      senior: # this is just a label
        approvals_required: 1
        name: "Senior SRE"
        users:
          - senior-sre-1
          - senior-sre-2
        protected_branches:
          - production
          - staging
      any: # this is just a label
        approvals_required: 1
        name: "Any member"
        rule_type: any_approver
      enforce: true
```
