### ISSUE TITLE
Project members setting ignores case

### ISSUE THREAD

**Issue by wrbbz** [gitlabform/gitlabform#770]
**Describe the bug**

I've got a config of gitlabform:
```yaml
  "path/to/project":
    members:
      keep_bots: true
      enforce: true
      groups:
        ACL/team:
          group_access: 30
```

When I call `gitlabform 'path/to/project` no new members added

The debug output shows following lines:

```
...
Setting group 'acl/team' as a member
...
Removing group 'ACL/team' that is not configured to be a member.
```

If I drop `enforce: true` config - everything is fine and the group is added as a member of the project.

Also, in debug output I can see, that group informations shows:
```
"GET /api/v4/groups/acl%2Fteam?per_page=100 HTTP/1.1" 200 None
<--- json = {... "full_path": "ACL/team"...}
```

Output of API call on project shows that group is already a member:
```
"GET /api/v4/projects/path%2Fto%2Fproject?per_page=100 HTTP/1.1" 200 None
<--- json = { ... {"expires_at": null, "group_access_level": 30, "group_full_path": "ACL/team", "group_id": ${someId}, "group_name": "Team"}, ...}
```

And after that call, I can see a message on removing member

I suppose, there are some problems with group case. That is ignored during member setting and not ignored during member check and removal

**GitLabForm version**

```bash
$ gitlabform -V
🏗 GitLabForm version: 3.11.1 = the latest stable 😊
```

**GitLab version**

`v16.11.1-ee`
