### ISSUE TITLE
Unclear error message when user is removed: Warning: Branch 'develop' not found when trying to set it as protected/unprotected!

### ISSUE THREAD

**Issue by hiaik** [gitlabform/gitlabform#790]
**Describe the bug**

with config.yml
```
projects_and_groups:
  "group/*":
    branches:
      develop:
        protected: true
        push_access_level: 0
        merge_access_level: 30
        unprotect_access_level: 40
        code_owner_approval_required: true
        allowed_to_push:
          - user_id: 1
          - user_id: 2

  "group/project":
    branches:
      develop:
        allowed_to_push:
          - user_id: 1
          - user_id: 2
          - user_id: 3
```

If `user_id: 3` was removed from gitlab, we will get:

**Issue 1**
`Warning` during processing "group/project" but it will be `error` in reality as "allowed_to_push" will not be processed as a result. If "group/project" has `schedules` config as well, it will get Inactive status (for Next Run column) as user who owns that schedule can not merge into develop due to bug with "allowed_to_push"

So it is a bug, not warning and "group/project" should be counted within ":: # of projects failed: <N>" at the end.
It is not counted there atm.

**Issue 2**
Current warning says `Warning: Branch 'develop' not found when trying to set it as protected/unprotected!` which is super confusing and hard to debug. Why not to show error that "user_id 3 does not exist" ?

**GitLabForm version**
4.12.0

**GitLab version**
16.11.1
