### ISSUE TITLE
use variable other than GITLAB_TOKEN when using CI/CD scheduled pipeline

### ISSUE THREAD

**Issue by oupala** [gitlabform/gitlabform#802]
**Describe the bug**

When using gitlabform in a scheduled pipeline, we don't want to use the variable GITLAB_TOKEN as this variable is used by numerous tools. We want to specify another variable so that gitlabform does not interfer with other tools.

It looks like it is not possible to use a variable in the config.yml file [as described in the documentation](https://gitlabform.github.io/gitlabform/reference/#minimal-working-config).

**GitLabForm version**

latest version of docker image: 3.11.1

**GitLab version**

GitLab Community Edition [v16.11.5](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v16.11.5)

**Comment by amimas** [comment]
Hi, gitlabform itself will use the `GITLAB_TOKEN` environment variable but you can use any other variable you wish to this one before executing gitlabform.

What does your pipeline config look like?

**Comment by oupala** [comment]
I made some test outside CI/CD, in a manually runned container, and I cannot manage to make it run.

1. I have an environment variable that is available in my environment as `GITLABFORM_TOKEN=glpat-redacted`
1. I have a minimal configuration file (see above)
1. I launch the following command: `gitlabform -k -c config.yml web`

```yaml
config_version: 3

gitlab:
  url: https://gitlab.my.instance
  # alternatively use the GITLAB_TOKEN environment variable
  token: "$GITLABFORM_TOKEN"

projects_and_groups:
  "web/*":
    project_settings:
      visibility: internal
```

We have a pipeline that is doing many housekeeping tasks and we want to use different variable for each tool so that each tool has its own access token with minimal access rights (chereas gitlabform often needs an owner access token with `api` and `write repository` rights.

**Comment by gdubicki** [comment]
I guess that @amimas meant that you can run gitlabform like this, @oupala:
```bash
GITLAB_TOKEN=$GITLABFORM_TOKEN gitlabform -k -c config.yml web
```
...with a config like:
```yaml
config_version: 3

gitlab:
  url: https://gitlab.my.instance
  # we use the GITLAB_TOKEN environment variable for providing the auth token

projects_and_groups:
  "web/*":
    project_settings:
      visibility: internal
```
Note that there is no `token` in this YAML.

**Comment by gdubicki** [comment]
We are open to PRs with such a change. 😊

**Comment by amimas** [comment]
> But what about a real solution such as:
> 
> * look for a GITLABFORM_TOKEN variable if there is one
> * if not, look for a GITLAB_TOKEN
> 
> This would allow gitlabform to use a specific variable, and if not such specific variable exist, use the generic gitlab token variable.

I'm not sure that actually is a real solution. To be honest, I don't understand the problem. Lots of other tools works this way, meaning they don't support "multiple environment variables" for the same thing. And even if you do support multiple environment variables, which order should they be in? The order of processing that satisfies your requirement might not satisfy someone else.

**Comment by oupala** [comment]
I proposed an order in my previous message: take the more specific variable if defined, then if not, the the more generic variable.

If you don't understand the problem I try to solve, let me explain it a bit.

I have a gitlab pipeline that is hosted inside a project named ` housekeeping`  which is in charge of all *housekeeping* tasks for a group or a subgroup.

- *gitlabform* is in charge of projects and groups configuration
- another job is in charge of purging old pipelines
- another job is in charge of linting files
- and so on

However, all tools are using the same variable named ` GITLAB_TOKEN`  whereas they don't require the same credential from the access token. For security concerns, I want to keep credentials as low as possible **for each job**. That means I can't use the same token for all tools. I then want to create a specific token for each tool:

- ` GITLABFORM_TOKEN`  for **gitlabform**
- ` GITLAB_PURGE_PIPELINES_TOKEN`  for the tool in charge of purging pipelines
- ` GITLAB_LINTER_TOKEN`  for the tool in charge of linting files
- ` GITLAB_ANOTHER_TOKEN`  for another tool
- and so on

I hope this is more clear now.

**Comment by amimas** [comment]
Can you share an example of another tool that supports using multiple variable for the same purpose?

When I said I don't understand the problem, I meant I don't see why you are not able to set/export the proper environment variable before running gitlabform?

The gitlab pipeline you explained sounds perfectly fine and logical. But it doesn't explain the problem though. As I said earlier, you can just configure necessary variable in each jobs before executing the tool. Maybe share your CI config to show where the problem is.

**Comment by mfriedenhagen** [comment]
One thing which I now saw. Before using gitlabform we used a standard tool user for our team which ran the pipeline schedules but had only role Maintainer. Now because we want to manage group settings as well we created a new group service account with role owner and that one owns the pipeline so the pipelines now run with somewhat extended permissions.

**Comment by Shackelford-Arden** [comment]
I second amimas's request to see the CI file you're referencing.

I'll expand the example set by @gdubicki a bit more to show how I would handle this scenario within a Gitlab CI file.

@oupala For your scenario of multiple tokens for specific purposes:

```yaml

run:
  environment:
    GITLAB_TOKEN: $GITLABFORM_TOKEN
  script:
    - gitlabform -k -c config.yml web
  rules:
    - if: $RUN_WEB == "yes"

purge pipelines:
  environment:
    GITLAB_TOKEN: $GITLAB_PURGE_PIPELINES_TOKEN
  script:
    - gitlabform -k -c config.yml pipeline_purge
  rules:
    - if: $RUN_PIPELINE_PURGE == "yes"

linter:
  environment:
    GITLAB_TOKEN: $GITLAB_LINTER_TOKEN
  script:
    - gitlabform -k -c config.yml lint
  rules:
    - if: $RUN_LINT == "yes"

another:
  environment:
    GITLAB_TOKEN: $GITLAB_ANOTHER_TOKEN
  script:
    - gitlabform -k -c config.yml another
  rules:
    - if: $RUN_ANOTHER == "yes"

```

Note here how this still allows you to have multiple jobs, each with their own use case, but still using the singular `GITLAB_TOKEN` environment variable when `gitlabform` is actually called/used.

My understanding says this would both handle your usecases and not require additional environment variable names in `gitlabform` directly. Please let me  know if I'm missing something :grin:
