### ISSUE TITLE
Protected tag returns "Name has already been taken" error

### ISSUE THREAD

**Issue by azzy5** [gitlabform/gitlabform#829]
**Describe the bug**

With the current implementation, when trying to project a tag we get following error, if the tag is already protected: 

```
> curl --request POST \
  --header "PRIVATE-TOKEN: $PJ_TAG" \
  --header "Content-Type: application/json" \
  --data '{"name": "test", "create_access_level": "40"}' \
  "https://gitlab.com/api/v4/projects/XYZ/protected_tags"
{"message":["Name has already been taken"]}%
``` 

However, if we check whether the tag is protected or not by running the following API call, we can avoid this error.

```
> curl --request GET --header "PRIVATE-TOKEN: $PJ_TAG" "https://gitlab.com/api/v4/projects/61955147/protected_tags/test"
{"name":"test","create_access_levels":[{"id":12807604,"access_level":40,"access_level_description":"Maintainers","deploy_key_id":null,"user_id":null,"group_id":null}]}%
``` 

https://docs.gitlab.com/ee/api/protected_tags.html#get-a-single-protected-tag-or-wildcard-protected-tag

**GitLabForm version**

*

Output of `gitlabform -V`
*

**GitLab version**

*

**Comment by hiaik** [comment]
happens on 3.14.1 version for us...

But issue is very intermittent and only happens for us when we process all our projects (~350). Random projects fail intermittently with that error.

**Comment by amimas** [comment]
Hi, thanks for opening the issue. The problem mentioned in the initial message is a bit unclear. Let's start with a sample gitlabform config you're using and how you execute gitlabform. Let's not jump to conclusion or solution before we identify the issue.

**Comment by hiaik** [comment]
Thanks @amimas! Interesting coincidence in time: once you added a comment, error happened 2 times over the weekend :)

Ticket was created by GitLab support team where I logged my issues initially. We are using gitlab saas (latest version) and do not have access to logs. GitLab support team was able to identify from logs that error is coming from calling `protected_tags` endpoint.

Last error happened today:
```
* ( 39/175) Processing project: viator/infrastructure/gitlab-directtransfer-scripts
Warning: Error occurred while processing project viator/infrastructure/gitlab-directtransfer-scripts, exception:
422: ['Name has already been taken']
```

There is no settings in config for `viator/infrastructure/gitlab-directtransfer-scripts`, so it is coming from group:

```yaml
"viator/infrastructure/*":
    project_settings:
      jobs_enabled: true
    project_push_rules:
      max_file_size: 20 # MB
    branches:
...
    merge_requests_approval_rules:
...
    deploy_keys:
....
    tags:
      "release/*":
        protected: true
        create_access_level: 40 # = Maintainer, see "valid access levels" at https://docs.gitlab.com/ee/api/members.html
    members:
        ...
```


Looking at above + logs from gitlab saas, we have found that when protected tags endpoint is called ( tag name "release/*") more than once -> we get that error.


Error is very intermittent. We process around 500 projects every hour and it happened 5 times so far. I can not replicate it by processing single projects (it happens only within the entire processing cycle ~500 projects).

**Comment by amimas** [comment]
Thanks @hiaik for the details.

> Looking at above + logs from gitlab saas, we have found that when protected tags endpoint is called ( tag name "release/*") more than once -> we get that error.

Wondering why the same tag will be processed multiple times? Do you also happen to have config at the top level group (i.e. `viator/*`)? And, how do you execute gitlabform (i.e. what parameters used?). Maybe try saving the effective config and then share the config generated for the affected project (i.e. `gitlabform -c <config-fle-path.yaml> -o <output-file-path.yaml>`). Then check to see if the affected project really contains same tag multiple times. Even if it did (although yaml wouldn't allow that I think), there is already existing code to try unprotect the tag first before attempting to protect it.

https://github.com/gitlabform/gitlabform/blob/1d27b098be39ddf54e8d71999516eeda5333fb9d/gitlabform/processors/project/tags_processor.py#L65-L70

Let's try the above. It might help with debugging the issue.

**Comment by hiaik** [comment]
Hi @amimas 

> Wondering why the same tag will be processed multiple times? Do you also happen to have config at the top level group (i.e. viator/*)?

No, top level does not have anything related to protected tags:

```
projects_and_groups:
  "viator/*":
    project_settings: ...
    deploy_keys: ...
    merge_requests_approvals: ...
    merge_requests_approval_rules: ...
    project_push_rules: ...
```


> And, how do you execute gitlabform (i.e. what parameters used?).

`gitlabform -c projects-config.yml ${PROJECT_PATH}`
where ${PROJECT_PATH} will be `viator/infrastructure`




>Maybe try saving the effective config and then share the config generated for the affected project (i.e. gitlabform -c <config-fle-path.yaml> -o <output-file-path.yaml>). Then check to see if the affected project really contains same tag multiple times. 


I have run (3.14.1 is our current version but I can not see duplicate values on 3.16.3 as well when running locally). It is a very intermittent issue at this stage.

```
docker run -it -e GITLAB_TOKEN=... -v $PWD:/app -w /app ghcr.io/gitlabform/gitlabform:3.14.1 sh -c 'gitlabform -o effective-config.yaml -c projects-config.yml "viator/infrastructure"'
```

For the project which was affected recently - no issues:
```
%YAML 1.2
---
...
viator/infrastructure/gitlab-directtransfer-scripts:
   project_settings: ...
   project_push_rules:...
   deploy_keys: ... 
   branches:
      master: ...
      develop: ...
      production: ...
      main: ...
   tags:
      release/*:
         protected: true
         create_access_level: 40
   members: ...
   merge_requests_approvals: ...
   merge_requests_approval_rules: ...
...
```



> Even if it did (although yaml wouldn't allow that I think),
Correct.


>there is already existing code to try unprotect the tag first before attempting to protect it.
Thanks for sharing... will be great to get to the bottom of that issue


Dmitry
