### ISSUE TITLE
403 error on protected_branches

### ISSUE THREAD

**Issue by philippe-granet** [gitlabform/gitlabform#872]
**Describe the bug**
With this conf:
```yaml
projects_and_groups:
  "project_group/*":
    branches:
      main:
        protected: true
 ````
if one project in group `project_group` is a `Issue-only` project:  

![image](https://github.com/user-attachments/assets/bc4b963d-585b-4044-a330-521293593422)

gitlabform command fail with this error:
```
...
* (178/183) Processing project: project_group/project_178
* (179/183) Processing project: project_group/project_179
Warning: Error occurred while processing project project_group/project_179, exception:
Request url='https://[redacted]/api/v4/projects/project_group%2Fproject_179/protected_branches/main?per_page=100', 
method=GET, failed - expected code(s) [200], got code 403 & body: '{"message":"403 Forbidden"}'
* (180/183) Processing project: project_group/project_180
* ...
:: # of groups processed successfully: 0
:: # of projects processed successfully: 182
:: # of projects failed: 1 
:: Failed project 179: project_group/project_179
```
**GitLabForm version**

`v3.16.4`

**GitLab version**

`v17.3.5`

**Comment by amimas** [comment]
Thanks for reporting @philippe-granet . I don't think there's a logic in the branch protection processor to check if repository is enabled or not. Can you contribute a fix?

The work-around I can think of right now is to explicitly configure branch protection to be skipped for these type of projects like this:

```yaml
projects_and_groups:
  "project_group/*":
    branches:
      main:
        protected: true
  "project_group/Issue-only":
    branches:
      skip: true
```

The above would probably apply to other type of processors too if they are not enabled (i.e. CI CD, Merge Requests, etc.) and similar work-around like above will also be true, I think.
