### ISSUE TITLE
Unexpected behavior when trying to add a protected branch that uses a wildcard. 

### ISSUE THREAD

**Issue by KieranSt97** [gitlabform/gitlabform#886]
**Describe the bug**

When attempting to use gitlab-form to configure wildcard-based branch protection (e.g., r-*), the tool fails to apply the protection, even if branches matching the wildcard (e.g., r-feature1, r-test) already exist in the repository. However the GitLab UI allows the creation of wildcard branch protection rules and successfully applies the protection to matching branches. (Even if no matching branches exist.) See the below screenshot as an example.

![gitlabissue](https://github.com/user-attachments/assets/b5f5f74c-f5d0-4441-b0d2-a05b644d95a6)

The following warning is shown when running gitlab-form:

```
Processing section 'branches'
Warning: Branch '*-some-name-suffix' not found when trying to processing it to be protected/unprotected!
Warning: Branch 'r-*' not found when trying to processing it to be protected/unprotected!
```

This can be reproduced using the following configuration (some of which was pulled directly from the documentation [here](https://gitlabform.github.io/gitlabform/reference/protected_branches/): 
```
config_version: 3
gitlab:
  ssl_verify: true
  timeout: 20
  url: https://gitlab.com

projects_and_groups:
  "group/project1":
    branches:
      'r-*':
        protected: true
        create: true
        allowed_to_merge: 
          - access_level: maintainer
        allowed_to_unprotect:
          - access_level: maintainer
        allowed_to_push:
          - access_level: no access
      '*-some-name-suffix':
        protected: true
        push_access_level: no access
        merge_access_level: developer
        unprotect_access_level: maintainer
```

**GitLabForm version**

`🏗 GitLabForm version:  4.0.3 = the latest stable 😊`

**GitLab version**

`17.6.0-pre`

Please could anyone advise on this? Am I missing anything here? Thanks!
