### ISSUE TITLE
group_members:enforce:true lead to deletion of users from SAML SSO

### ISSUE THREAD

**Issue by gosoly** [gitlabform/gitlabform#888]
We have SAML SSO configured at our company root level with about 400 ish users. eg:  https://gitlab.com/company_root

**Current Behaviour**
By trying to link another group to this root level as group member eg:
```
projects_and_groups:
  "company_root/*":
    group_members:
      enforce: true
      groups:
        company_root/groups/another_group:
          group_access: 40
```
The user_before which fetch from https://github.com/gitlabform/gitlabform/blob/f96efbe89ad4ae707a5d55ff476be825b8bb16d2/gitlabform/processors/group/group_members_processor.py#L175  seems to have all users from SAML SSO.
and then with `enforce: true` it basically go deleting all those SAML SSO users from group https://github.com/gitlabform/gitlabform/blob/f96efbe89ad4ae707a5d55ff476be825b8bb16d2/gitlabform/processors/group/group_members_processor.py#L266-L268

 
**Suggested Behaviour**
SAML SSO users should not be included in these when enforce as this will cause destructive results by deleting the membership link for those SAML SSO users. The SAML user still exists in Gitlab but it will need to be re-auth to create the membership again and they will also be removed as project/group members as well and need to be assigned back after re-auth.
