### ISSUE TITLE
Why is projects_and_groups a required key?

### ISSUE THREAD

**Issue by szEvEz** [gitlabform/gitlabform#900]
Hi,

I am trying to manage the application config with gitlabform.

```yaml
config_version: 3
gitlab:
  url: "{{ gitlab_url }}"
  token: "{{ gitlab_token }}"
application:
  settings:
    dsa_key_restriction: -1
    prevent_merge_requests_author_approval: true
    disable_overriding_approvers_per_merge_request: true
    prevent_merge_requests_committers_approval: true
    default_branch_name: main
```

Unfortunately, this just breaks and I need to have the project_and_groups key defined.

Is that by design? Is there some way around?
