### ISSUE TITLE
Implement add/update/delete project topics

### ISSUE THREAD

**Issue by jimisola** [gitlabform/gitlabform#925]
Implement so that projects topics can be added, updated and deleted for projects.

Project Topics are set using [Edit Project](https://docs.gitlab.com/ee/api/projects.html#edit-a-project) and its `topics` attribute.

**Comment by jimisola** [comment]
Since topics is just an attribute I reckon one could do:

```
projects_and_groups:
  group_1/project_1:
    project_settings:
      topics: ["topic1", "topic1"]
```

but that would then update and overwrite any existing topic(s) correct?

Is there a generic way to control whether to overwrite or not?

**Comment by amimas** [comment]
Hi @jimisola - Your config syntax looks alright to me. It should work fine. Have you tried it yet? You can even use native yaml syntax. For example:

```yaml
projects_and_groups:
  group_1/project_1:
    project_settings:
      topics:
        - "topic1"
        - "topic2"
```

> but that would then update and overwrite any existing topic(s) correct?
> Is there a generic way to control whether to overwrite or not? If not, then this issue (feature) is valid.

According to the [GitLab's Edit Project API](https://docs.gitlab.com/ee/api/projects.html#edit-a-project), this will replace/overwrite any existing topics. This is just how the API works.

<img width="918" alt="Image" src="https://github.com/user-attachments/assets/72e7d7ea-8583-4ac4-b1f6-e2a0e26ce85f" />
