### ISSUE TITLE
approval_rules in protected_environments are not working

### ISSUE THREAD

**Issue by ryanoolala** [gitlabform/gitlabform#938]
**Describe the bug**

`protected_environments.{env}.approval_rules` does not work, furthermore if there is an existing approval rule set on the UI, applying gitlabform config will overwrite the existing approval rules by removing it.

```yaml
protected_environments:
      production:
        deploy_access_levels:
          - access_level: developer
        approval_rules: # Not working as of v4.1.1
          - group_id: xxx
            required_approvals: 2
```

**GitLabForm version**

Output of `gitlabform -V`
v4.1.1

**GitLab version**

F.e. `v17.7.3-ee`
