### ISSUE TITLE
Breaking inheritance validation error in 4.1.2

### ISSUE THREAD

**Issue by gosoly** [gitlabform/gitlabform#942]
We have the higher level config: 
```
  "viator/infrastructure/*":
    project_settings:
      jobs_enabled: true
    project_push_rules:
      max_file_size: 20 # MB
    branches:
      master: *default_branch_settings
      develop: *default_branch_settings
      production: *default_branch_settings
      main: *default_branch_settings
    merge_requests_approval_rules:
      inherit: false
      infrastructure:
        name: "Any approver in the Infrastructure team"
        approvals_required: 1
        groups:
          - viator/org/infrastructure
      enforce: true
```
and it applied the merge_requests_approval_rules on below fine without `merge_requests_approval_rules`
```
"viator/infrastructure/terraform/database-users"
    .....
```
4.1.2 show error 
```
🏗 GitLabForm version: 4.1.2 = the latest stable 😊
Warning: Connected as non-admin. You may encounter permission issues.
Running in dry-run mode...
>>> Getting requested groups or projects...
Error: The inheritance-break flag set in "viator/infrastructure/aws/aws-workspace-scripts" under key "merge_requests_approval_rules" is invalid
because it has no higher level setting to inherit from.
```
project config:
```
  "viator/infrastructure/aws/aws-workspace-scripts":
    merge_requests_approval_rules:
      inherit: false
      infrastructure_or_devx: *infrastructure_or_devx_merge_requests_approval_rule
      enforce: true
```

These same configuration show no above error when run using 4.1.1

**Comment by amimas** [comment]
Hi @gosoly - Could you please clarify or post the full config? It was kind of hard to follow the issue you described. I'll try to rephrase it below and let me know if I got it wrong.

Your config looks like this (removed a few things that aren't relevant):

```yaml
  "viator/infrastructure/*":
    merge_requests_approval_rules:
      inherit: false
      infrastructure:
        name: "Any approver in the Infrastructure team"
        approvals_required: 1
        groups:
          - viator/org/infrastructure
      enforce: true
  "viator/infrastructure/aws/aws-workspace-scripts":
    merge_requests_approval_rules:
      inherit: false
      infrastructure_or_devx: *infrastructure_or_devx_merge_requests_approval_rule
      enforce: true
```

What command did you use when you ran gitlabform? I understand you're getting the following error message right now:

```
Error: The inheritance-break flag set in "viator/infrastructure/aws/aws-workspace-scripts" under key "merge_requests_approval_rules" is invalid
because it has no higher level setting to inherit from.
```

What stood out to me at a glance is that the error makes sense. I see you have `inherit: false` set on `viator/infrastructure/*`. And then you have `inherit: false` set on `viator/infrastructure/aws/aws-workspace-scripts`. So, if you follow the hierarchy, the config doesn't define a `merge_requests_approval_rules` anywhere higher up. If that's not defined, breaking inheritance doesn't make sense, right?

Is it possible that the sample config you've shared is incomplete?

**Comment by gosoly** [comment]
Isn't the `merge_requests_approval_rules:inherit: false` on `viator/infrastructure/*` just break inheritance from `viator/*` ?  it doesn't break inheritance down the hierarchy from there I believe? This is why I used to mention another keyword to prevent child inheritance at parent etc but I don't think we got it yet right?  Which means after breaking inheritance. it redefined `merge_requests_approval_rules` at `viator/infrastructure/*` and that is carried over to all sub-paths.  so not sure why in `viator/infrastructure/aws/aws-workspace-scripts` it give that error....

Also, Like I mentioned. This only happen on 4.1.2. if I run it using 4.1.1 with exact same config files I don't get any of these error at all.

**Comment by amimas** [comment]
> Isn't the `merge_requests_approval_rules:inherit: false` on `viator/infrastructure/*` just break inheritance from `viator/*` ?

Yes, I think so. But, your config sample didn't show what's setup for `viator/*`. That's why I mentioned above that your sample config is probably incomplete. Could you please share the complete config? You can take out unnecessary parts of the config (i.e. project settings, branch protection, etc.), but having a complete config would be helpful. Another option is you can add a new test case in a separate PR that reproduces the issue.

> This only happen on 4.1.2. if I run it using 4.1.1 with exact same config files I don't get any of these error at all.

It's possible that something in the new release broke the behaviour unexpectedly. It's difficult though to tell what may have changed or broke the behaviour. You can see the changes that were made in [release 4.1.2](https://github.com/gitlabform/gitlabform/releases/tag/v4.1.2). Only relevant item that might have contributed to this is probably #939, but as I said it's not clear. It's also possible that the previous behaviour was incorrect and now it's been fixed in v4.1.2.

Anyways, let's start with a clear and complete config sample. The easier it is to reproduce, the better. Thanks.

**Comment by gosoly** [comment]
@amimas here is the short config I try to test it
```
projects_and_groups:
  "viator/*":
    merge_requests_approval_rules:
      any:
        name: "Any approver in project"
        approvals_required: 1
        rule_type: any_approver
      enforce: true      
  "viator/devx-test-path/*":
    merge_requests_approval_rules:
      inherit: false
      devx:
        name: "Any approver in the DevX team"
        approvals_required: 1
        groups:
          - viator/org/devx
      enforce: true
  "viator/devx-test-path/devx-test-nested-path/devx-blank-project":
    merge_requests_approval_rules:
      inherit: false
      devx-and-infrastructure:
        name: "Any approver in the DevX and Infrastructure team"
        approvals_required: 1
        groups:
          - viator/org/devx
          - viator/org/infrastructure
      enforce: true   
```
and here is when run it same config above between 4.1.1 vs 4.1.2
4.1.1 run without any issue
```
$ docker run -it -e GITLAB_TOKEN=XXXXXXXX -v $PWD:/app -w /app ghcr.io/gitlabform/gitlabform:4.1.1 sh -c 'gitlabform -c projects-config.yml --noop viator/devx-test-path/devx-test-nested-path/devx-blank-project'
🏗 GitLabForm version: 4.1.1 = outdated 😔 , please update! (the latest stable is 4.1.2)
Warning: Connected as non-admin. You may encounter permission issues.
Running in dry-run mode...
>>> Getting requested groups or projects...
:: # of groups to process: 0
:: # of projects to process: 1
* (1/1) Processing project: viator/devx-test-path/devx-test-nested-path/devx-blank-project
:: # of groups processed successfully: 0
:: # of projects processed successfully: 1
:: All requested groups/projects processed successfully! ✨
```
but it failed validation on 4.1.2
```
$ docker run -it -e GITLAB_TOKEN=XXXXXXXX -v $PWD:/app -w /app ghcr.io/gitlabform/gitlabform:4.1.2 sh -c 'gitlabform -c projects-config.yml --noop viator/devx-test-path/devx-test-nested-path/devx-blank-project'
🏗 GitLabForm version: 4.1.2 = the latest stable 😊
Warning: Connected as non-admin. You may encounter permission issues.
Running in dry-run mode...
>>> Getting requested groups or projects...
Error: The inheritance-break flag set in "viator/devx-test-path/devx-test-nested-path/devx-blank-project" under key "merge_requests_approval_rules" is invalid
because it has no higher level setting to inherit from.
```

**Comment by amimas** [comment]
@gosoly - Thanks for sharing the config. I tried to reproduce the issue but couldn't. Here's what I tried.

The following config shows 1 group with a nested config breaking the inheritance.

```yaml
config_version: 3

projects_and_groups:
  test-group/*:
    merge_requests_approval_rules:
      any:
        name: "Any approver in project"
        approvals_required: 1
        rule_type: any_approver
      enforce: true      
  test-group/test-project:
    merge_requests_approval_rules:
      inherit: false
      devx:
        name: "minimim 2 approval"
        approvals_required: 2
      enforce: true
```

```sh
$ gitlabform --noop --config gf-config.yml test-group/test-project
🏗 GitLabForm version: 4.1.2 = the latest stable 😊
Running in dry-run mode...
>>> Getting requested groups or projects...
:: # of groups to process: 0
:: # of projects to process: 1
* (1/1) Processing project: test-group/test-project
:: # of groups processed successfully: 0
:: # of projects processed successfully: 1
:: All requested groups/projects processed successfully! ✨
```

The above didn't seem to give me the error you're getting. Thought I'd try to add nested sub-group and project like yours.

```yaml
config_version: 3

projects_and_groups:
  test-group/*:
    merge_requests_approval_rules:
      any:
        name: "Any approver in project"
        approvals_required: 1
        rule_type: any_approver
      enforce: true      
  test-group/test-subgroup/*:
    merge_requests_approval_rules:
      inherit: false
      devx:
        name: "minimim 2 approval"
        approvals_required: 2
      enforce: true
  test-group/test-subgroup/test-subgroup-project:
    merge_requests_approval_rules:
      inherit: false
      devx:
        name: "minimim 3 approval"
        approvals_required: 3
      enforce: true
```

```sh
$ gitlabform --noop --config gf-config.yml test-group/test-subgroup/test-subgroup-project
🏗 GitLabForm version: 4.1.2 = the latest stable 😊
Running in dry-run mode...
>>> Getting requested groups or projects...
:: # of groups to process: 0
:: # of projects to process: 1
* (1/1) Processing project: test-group/test-subgroup/test-subgroup-project
:: # of groups processed successfully: 0
:: # of projects processed successfully: 1
:: All requested groups/projects processed successfully! ✨
```

But... I was able to reproduce the issue if I add the config for skipping the group containing the target project. See the `skip_groups` section in the config below:

```yaml
config_version: 3

projects_and_groups:
  test-group/*:
    merge_requests_approval_rules:
      any:
        name: "Any approver in project"
        approvals_required: 1
        rule_type: any_approver
      enforce: true      
  test-group/test-subgroup/*:
    merge_requests_approval_rules:
      inherit: false
      devx:
        name: "minimim 2 approval"
        approvals_required: 2
      enforce: true
  test-group/test-subgroup/test-subgroup-project:
    merge_requests_approval_rules:
      inherit: false
      devx:
        name: "minimim 3 approval"
        approvals_required: 3
      enforce: true


skip_groups:
  - test-group/test-subgroup/*
```

```sh
$ gitlabform --noop --config gf-config.yml test-group/test-subgroup/test-subgroup-project
🏗 GitLabForm version: 4.1.2 = the latest stable 😊
Running in dry-run mode...
>>> Getting requested groups or projects...
Error: The inheritance-break flag set in "test-group/test-subgroup/test-subgroup-project" under key "merge_requests_approval_rules" is invalid
because it has no higher level setting to inherit from.
```

If you also have similar `skip_groups` config, then I'd say the error message is valid and the fix in v4.1.2 I mentioned previously basically addressed an existing bug.

Hope that makes sense. Please reply back in case I missed something.

**Comment by amimas** [comment]
@gosoly - Did you get a chance to review my finding? Are you using `skip_group`?

Regardless, I think it's worth discussing it a bit more.

> If you also have similar skip_groups config, then I'd say the error message is valid and the fix in v4.1.2 I mentioned previously basically addressed an existing bug.

I had been thinking about this for a bit. My initial thought was that the current behaviour makes sense. But, I can see how it might be expected the other way too. I think it really depends on the definition of `skip_group`. If a group is being skipped, what does that mean?

Maybe `skip_group` only means, don't **apply** the changes to that "group" but use it for config processing. In that case, projects under that group should continue to inherit configs from the group. But, is that an appropriate expectation? What if someone expects it the way it is now?

What's your thought @gdubicki @TimKnight-DWP @jimisola ?

**Comment by gosoly** [comment]
Hi @amimas yes you're right we do have 
```
skip_groups:
  - viator/*
```

At some point in time we split groups related config and projects related config into two separate files. I'm not sure why I had that skip_groups in project config file back then.... 

Anyway, I try to generate effective configuration after remove skip_groups above in project config file by running:

```
docker run -it -e GITLAB_TOKEN=XXXXX -v $PWD:/app -w /app ghcr.io/gitlabform/gitlabform:4.1.1 sh -c 'gitlabform -c projects-config.yml --noop -o effective_config_after_4.1.1.txt --debug viator' > debug_after_4.1.1.log
```
vs
```
docker run -it -e GITLAB_TOKEN=XXXXX -v $PWD:/app -w /app ghcr.io/gitlabform/gitlabform:4.1.2 sh -c 'gitlabform -c projects-config.yml --noop -o effective_config_after_4.1.2.txt --debug viator' > debug_after_4.1.2.log
```
comparing effective_config_after_4.1.1.txt with effective_config_after_4.1.2.txt has identical content.

then also run similar but with `viator/engineering` (we also has to split run a few sub paths to apply configuration since there are a couple one that huge and take too long time)
```
docker run -it -e GITLAB_TOKEN=XXXXX -v $PWD:/app -w /app ghcr.io/gitlabform/gitlabform:4.1.1 sh -c 'gitlabform -c projects-config.yml --noop -o effective_config_engineering_after_4.1.1.txt --debug viator/engineering' > debug_after_engineering_4.1.1.log
```
vs
```
docker run -it -e GITLAB_TOKEN=XXXXX -v $PWD:/app -w /app ghcr.io/gitlabform/gitlabform:4.1.2 sh -c 'gitlabform -c projects-config.yml --noop -o effective_config_engineering_after_4.1.2.txt --debug viator/engineering' > debug_after_engineering_4.1.2.log
```
comparing effective_config_engineering_after_4.1.1.txt with effective_config_engineering_after_4.1.2.txt also has identical content.

I also try to compare debug output between them but only saw some hashes and updated_at timestamp difference.
however, I saw some json logging that seems to only happen when call api with per_page parameter (my guess) but I don't get it why it use it on only few projects in 4.1.2 but seems all in 4.1.1 

eg:
<img width="1149" alt="Image" src="https://github.com/user-attachments/assets/6466524c-7e5c-4b4e-9f1b-388011c8128d" />
vs

<img width="1153" alt="Image" src="https://github.com/user-attachments/assets/3f06ab5b-f754-4556-b9e9-82359ba22f62" />

Also, could you help clarify the following for me:
- dry-run debug isn't going to be the same as non-dry-run one right? since you might shortcut some call in code earlier etc
- I can't generate effective configuration without removing skip_groups above in 4.1.2 since it failed validation so it hard to tell what will happen when you have skip_groups at root like that. Does that means no projects will be processed at all? 
- when you use keyword 'group' does it refer to paths that's not project node etc in Gitlab? or it means group specific sections?

**Comment by amimas** [comment]
@gosoly - Thanks for checking and glad to hear that by removing the `skip_group`, now it's not failing or giving you the original issue.

Not too sure about the logging though. I didn't follow if/what issue you noticed. It's possible that the logging is not exactly like before since there were some refactoring of `project_settings` processor in [v4.1.2](https://github.com/gitlabform/gitlabform/releases/tag/v4.1.2). 

> dry-run debug isn't going to be the same as non-dry-run one right? since you might shortcut some call in code earlier etc

That's true. The dry-run doesn't go through all the logics. For example: it will not test the logics involving making API calls to gitlab (there aren't any dry-run option from gitlab's api).

> I can't generate effective configuration without removing skip_groups above in 4.1.2 since it failed validation so it hard to tell what will happen when you have skip_groups at root like that. Does that means no projects will be processed at all?

I don't think it means no projects will be processed. I believe it means the group itself won't be processed.

> when you use keyword 'group' does it refer to paths that's not project node etc in Gitlab? or it means group specific sections?

Sorry, not sure what you mean. Could you clarify or give some examples?

> Could you help double confirm me that the effective configuration output from using -o option would give exactly the same effective config as when we're not doing dryrun? I need to ensure that removing that skip_groups won't change any configurations in anyway etc.

Sorry, I can't exactly guarantee as I don't know the history of your config and usage and why `skip_group` was used previously.   I wouldn't expect a different behaviour though since during apply/non-dry-run phase gitlabform would use the same effective config and looks like the effective config being generated between 4.1.1 and 4.1.2 is same.

Hope that helps.

**Comment by TimKnight-DWP** [comment]
@amimas I will take a look through this issue and code changes, looks like we're seeing something similar too on merge_request_approval_rules

**Comment by TimKnight-DWP** [comment]
Group level:
```yaml
  "X/A/*":
    group_settings:
      share_with_group_lock: false
      membership_lock: false

    merge_requests_approvals:
      merge_requests_disable_committers_approval: true
      require_reauthentication_to_approve: true

    merge_requests_approval_rules:
      enforce: true
      code_coverage:
        applies_to_all_protected_branches: true
        approvals_required: 1
        name: "Coverage-Check"
        users:
          - adam-moss
          - gokul.rajendran1
          - jack.hindley
          - lewis.wood2
          - robert.hill1
          - sachin.singh8
          - tim.knight1
        report_type: code_coverage
        rule_type: report_approver
     review:
        applies_to_all_protected_branches: true
        approvals_required: 1
        name: "Review"
        users:
          - adam-moss
          - gokul.rajendran1
          - jack.hindley
          - lewis.wood2
          - robert.hill1
          - sachin.singh8
          - tim.knight1
        rule_type: regular

  "X/A/gitlab-configuration":
    project_settings:
      wiki_access_level: private
    merge_requests_approval_rules:
      enforce: true
      any:
        approvals_required: 1
        name: "Any member"
        rule_type: any_approver
```

The Repo "Gitlab-configuration" is still having the code_coverage rule applied to it

**Comment by TimKnight-DWP** [comment]
Prior to a recent refactor we had the following in the gitlab-configuration merge_requests_approval_rules, I wonder if that was a workaround
```yaml
      code_coverage:
        applies_to_all_protected_branches: true
        approvals_required: 0
        name: "Coverage-Check"
        users:
          - adam-moss
          - gokul.rajendran1
          - jack.hindley
          - lewis.wood2
          - mahadevan.karthi
          - robert.hill1
          - sachin.singh8
          - tim.knight1
        report_type: code_coverage
        rule_type: report_approver
```

**Comment by TimKnight-DWP** [comment]
The reason this ends up happening, is because in `_merge_configs` in `core.py` it merges together the group and project level settings with project winning if there is a more specific configuration of the same implementation i.e. where we set approvals_required to 0.

I don't think this is a bug, I think it's currently intended functionality, which in most cases allows for **additive** information from Groups into Projects.

If we wanted to change this, we'd have to update `projects.py` or `core.py` to allow Project-level set "enforce" to throw away anything from the Group-level. But that feels like a massive change at a fundamental level. Thoughts @gdubicki @amimas @jimisola @adam-moss ?

In most cases if you set a more stringent/specific setting at the Group level you absolutely **want** it to be enforced/apply down in the Project levels

------------------------

The workaround is to set any group level mr_approval_rules you don't want to apply at the Project level to `approvals_required: 0`

**Comment by adam-moss** [comment]
> I don't think this is a bug, I think it's currently intended functionality, which in most cases allows for **additive** information from Groups into Projects.

This seems counter to the purpose of `enforce: true` to me.  Personally I would expect additive rules to not require enforce.

> In most cases if you set a more stringent/specific setting at the Group level you absolutely **want** it to be enforced/apply down in the Project levels

Isn't this what `inherit: false` and the opposite `enforce: true` are intending?  Explicit over implict?
 
> The workaround is to set any group level mr_approval_rules you don't want to apply at the Project level to `approvals_required: 0`

Again, personally, I'd say this is a fudge, but then approval rules in general aren't flexible enough upstream.

**Comment by amimas** [comment]
> in `_merge_configs` in `core.py` it merges together the group and project level settings with project winning if there is a more specific configuration of the same implementation

> I don't think this is a bug, I think it's currently intended functionality, which in most cases allows for additive information from Groups into Projects.

That's correct @TimKnight-DWP. In your case, I think what you needed is the following config for the specific project:

```yaml
  "X/A/gitlab-configuration":
    merge_requests_approval_rules:
      inherit: false
      enforce: true
      any:
        approvals_required: 1
        name: "Any member"
        rule_type: any_approver
```

Thinking out loud here about how those 2 work. The `enforce` key is mostly about managing a setting that contains a list of entities (i.e. list of users or groups as member, list of pipeline schedules, list of variables, deploy keys, webhooks, etc.). Basically when this is enabled (i.e. `enforce: true`) for those entities, it means **delete** the entities that may exist in GitLab (maybe from prior config or manually configured) but not in the given config of the current execution of gitlabform.

The `inherit: false` on the other hand has nothing to do with gitlab. It's main purpose is for us to be able to write configs without a lot of efforts or duplication. In the end, gitlabform would generate a more detailed config that applies to every group or project and then use it for processing them.

So, in your case without `inherit: false` exists, the generated config for project probably looks like this:

```yaml
  "X/A/gitlab-configuration":
    merge_requests_approval_rules:
      enforce: true
      code_coverage:
        applies_to_all_protected_branches: true
        approvals_required: 1
        name: "Coverage-Check"
        users:
          - adam-moss
          - gokul.rajendran1
          - jack.hindley
          - lewis.wood2
          - robert.hill1
          - sachin.singh8
          - tim.knight1
        report_type: code_coverage
        rule_type: report_approver
     review:
        applies_to_all_protected_branches: true
        approvals_required: 1
        name: "Review"
        users:
          - adam-moss
          - gokul.rajendran1
          - jack.hindley
          - lewis.wood2
          - robert.hill1
          - sachin.singh8
          - tim.knight1
        rule_type: regular
      any:
        approvals_required: 1
        name: "Any member"
        rule_type: any_approver
```

Is that right? You only mentioned `code_coverage` rule existing for the project but I would've expected the `review` rule too.

It does seem a little counter intuitive, but does that align with what you're seeing?
