### ISSUE TITLE
SAML: saml_group_links does not update access_level for existing groups

### ISSUE THREAD

**Issue by rrotaru** [gitlabform/gitlabform#994]
https://github.com/gitlabform/gitlabform/blob/f96efbe89ad4ae707a5d55ff476be825b8bb16d2/gitlabform/processors/group/group_saml_links_processor.py#L33

I have noticed that when configuring `saml_group_links` for a group, any later updates to `access_level` for those groups are ignored (it seems like the desired behavior would be to delete and re-create the SAML link with the new `access_level`

**Comment by amimas** [comment]
Thanks for the report. Could you please post the gitlabform config you're using (both before and after update)? This is to better clarify the issue.

**Comment by rrotaru** [comment]
I'm using something like this:

```yml
  "my-org/main-projects/*":
    saml_group_links:
      enforce: true
      some_team:
        saml_group_name: some_team_saml
        access_level: developer
```

When the SAML Group link for `some_team_saml` already exists with a different role, it is not evaluated by the tool. The [SAML API](https://docs.gitlab.com/api/saml/#saml-group-links) does not have an "Update" endpoint, so the behavior I would expect is for the tool to remove the existing SAML group link and add a new one with the same SAML group name but the new access level.

Thank you for taking a look at this. I'm also happy to PR a change to add this fix/feature if it sounds like the desired behavior is what I outlined above.
