### ISSUE TITLE
Missing Target Parameter Error in GitLabForm Execution

### ISSUE THREAD

**Issue by maximilienkohl** [gitlabform/gitlabform#995]
### Bug Report

**Describe the bug**

When executing the GitLabForm command in the CI/CD pipeline, the command fails with an error indicating that the target parameter is required, even when running in no-op mode with the provided configuration file.

**GitLabForm version**

4.2.0

**GitLab version**

GitLab.com (latest version)

**Error Message**

```
$ gitlabform --skip-version-check --noop --config config.yml
🏗 GitLabForm version: 4.2.0 
Error: target parameter is required.
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1
```

**Code Snippets**

**.gitlab-ci.yml**
```yaml
image: ghcr.io/gitlabform/gitlabform:latest

some_project:
  script:
    - gitlabform --help
    - gitlabform --skip-version-check --noop --config config.yml
```

**config.yml**
```yaml
config_version: 3

gitlab:
  url: https://gitlab.com

projects_and_groups:
  "myprivategroup/*":
    project_settings:
      visibility: private
```
